import { defineType } from "sanity";
import { list, obj, objects, paragraphs, str, txt } from "../fields";
import { languageField } from "../shared";

/** One per language: interface strings (Ui), Person, formats, tools, recommendations, 404 and thank-you texts. */
export default defineType({
  name: "siteSettings",
  title: "Site settings",
  type: "document",
  groups: [
    { name: "ui", title: "Interface", default: true },
    { name: "person", title: "Person" },
    { name: "lists", title: "Formats, tools, recommendations" },
    { name: "pages", title: "404 and thank you" },
  ],
  fields: [
    languageField,
    obj(
      "ui",
      [
        list("nav", "link", { title: "Main navigation" }),
        str("tagline"),
        str("bookConsultation", { title: "Book a consultation (button)" }),
        str("menu"),
        str("close"),
        str("switchLanguage"),
        str("breadcrumbHome"),
        txt("footerText"),
        str("footerServices"),
        str("footerSite"),
        str("footerContact"),
        list("footerSiteLinks", "link"),
        str("privacy"),
        str("allCaseStudies"),
        str("allArticles"),
        str("readArticle"),
        str("featured"),
        str("minRead"),
        str("seeCaseStudy"),
        str("relatedCaseStudy"),
        str("relatedService"),
        str("relatedArticles"),
        str("toc", { title: "Table of contents" }),
        str("aboutLink"),
        str("replyNote"),
        str("placeholderFigures"),
        str("schematicCaption"),
        str("dashboardCaption"),
        str("portraitPlaceholder"),
        str("recommendationPlaceholder"),
        str("allFilter"),
        objects("topics", [str("key", { description: "assortment | pricing | product-data | reporting" }), str("label")], {
          title: "Case study topics (slicer)",
          preview: { title: "label", subtitle: "key" },
        }),
        obj("slicer", [str("slicer"), str("clear"), str("chart")]),
        obj("statusBar", [str("ready"), str("average"), str("count"), str("sum"), str("words"), str("characters"), str("value")]),
        obj("pagination", [str("prev"), str("next"), str("page")]),
        obj("video", [str("play"), str("transcript")]),
        str("calculatorHint", { description: "Shown under every calculator" }),
        str("calculatorMore", { description: "Link under an embedded calculator to its own page" }),
        obj(
          "form",
          [
            str("name"),
            str("company"),
            str("email"),
            str("task"),
            str("taskPlaceholder"),
            str("timeline"),
            str("language"),
            str("submit"),
            str("sending"),
            txt("privacyNote"),
            str("required"),
            str("invalidEmail"),
            txt("error"),
            str("workEmail"),
            str("emailPlaceholder"),
            str("phoneRequired"),
            str("phoneOptional"),
            str("invalidPhone"),
            str("channelLegend"),
            str("channelShort"),
            obj("channels", [str("email"), str("whatsapp"), str("phone")]),
          ],
          { title: "Contact form" },
        ),
        obj("languages", [str("en"), str("pl"), str("ru")], { title: "Language names" }),
        obj("cookie", [str("title"), txt("text"), str("accept"), str("reject"), str("policy")], { title: "Cookie banner" }),
      ],
      { title: "Interface strings", group: "ui", collapsed: false },
    ),
    obj(
      "person",
      [
        str("name"),
        str("jobTitle"),
        txt("shortBio"),
        str("signature"),
        str("email"),
        str("location"),
        str("timezone"),
        str("linkedin", { title: "LinkedIn URL" }),
        list("languages", "fact", { title: "Languages (language → level)" }),
        str("educationChip"),
      ],
      { group: "person", collapsed: false },
    ),
    list("formats", "consultingFormat", { title: "Consulting formats", group: "lists" }),
    list("tools", "toolItem", { group: "lists" }),
    list("recommendations", "recommendation", { group: "lists", description: "Only real ones, quoted with permission" }),
    obj(
      "notFound",
      [
        str("eyebrow"),
        str("h1", { title: "H1" }),
        txt("text"),
        str("note"),
        str("chartLabel"),
        str("nextTitle"),
        objects("links", [str("title"), txt("text"), str("href", { description: "Internal path, e.g. /services" })], {
          preview: { title: "title", subtitle: "href" },
        }),
      ],
      { title: "404 page", group: "pages" },
    ),
    obj(
      "thankYou",
      [
        str("contactTitle"),
        txt("contactText"),
        str("nextTitle"),
        paragraphs("next"),
        str("caseStudiesLink"),
        str("templatesLink"),
        str("templatesTitle"),
        txt("templatesText"),
        str("sent"),
        str("whileYouWait"),
        str("close"),
      ],
      { title: "Thank-you texts", group: "pages" },
    ),
  ],
  preview: {
    select: { language: "language" },
    prepare: ({ language }) => ({ title: "Site settings", subtitle: language?.toUpperCase() }),
  },
});
