import type { Category, Post } from "../../types";

export const categories: Category[] = [
  {
    slug: "power-bi",
    label: "Power BI",
    h1: "Power BI for Retail Analytics: Articles and Guides",
    intro: "DAX patterns, data models and dashboard structures for sell-through, stock cover and margin reporting in fashion retail.",
    serviceSlug: "power-bi-dashboards",
    seo: { title: "Power BI for Retail Analytics: Articles and Guides", description: "DAX patterns, data models and dashboards for sell-through, stock cover and margin reporting in fashion retail." },
  },
  {
    slug: "assortment",
    label: "Assortment",
    h1: "Assortment Planning Articles for Fashion Retail",
    intro: "Range architecture, size curves and buy planning explained with examples from fashion retail.",
    serviceSlug: "assortment-planning",
    seo: { title: "Assortment Planning Articles for Fashion Retail", description: "Range architecture, size curves and buy planning for fashion and retail teams." },
  },
  {
    slug: "pricing",
    label: "Pricing",
    h1: "Retail Pricing and Markdown Analysis Articles",
    intro: "Price ladders, cross-market pricing and markdown decisions based on data.",
    serviceSlug: "retail-pricing-analysis",
    seo: { title: "Retail Pricing and Markdown Analysis Articles", description: "Price ladders, cross-market pricing and markdown analysis for fashion retail." },
  },
  {
    slug: "product-data",
    label: "Product data",
    h1: "Product Data and PLM Articles for Fashion Brands",
    intro: "Attribute dictionaries, PLM data quality and governance rules that hold across markets.",
    serviceSlug: "product-data-quality-plm",
    seo: { title: "Product Data and PLM Articles for Fashion Brands", description: "Attribute dictionaries, PLM data quality and governance for fashion brands." },
  },
  {
    slug: "excel",
    label: "Excel",
    h1: "Excel for Retail Planning: Articles and Templates",
    intro: "Open-to-buy, buy plans and margin models in Excel that planners can maintain.",
    serviceSlug: "excel-retail-planning-models",
    seo: { title: "Excel for Retail Planning: Articles and Templates", description: "Open-to-buy, buy plan and margin models in Excel for retail planners." },
  },
];

const lorem = (topic: string) =>
  `Placeholder text about ${topic}. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`;

export const posts: Post[] = [
  {
    slug: "sell-through-rate-power-bi",
    category: "power-bi",
    title: "How to Calculate Sell-Through Rate in Power BI",
    h1: { before: "How to Calculate Sell-Through Rate in", accent: "Power BI" },
    excerpt: "The DAX pattern, the two denominators retailers confuse, and how to show it by week.",
    lead: "Two denominators, one DAX pattern, and the weekly view that makes sell-through usable in a buying meeting.",
    date: "2026-06-10",
    readingMinutes: 8,
    cover: "bars",
    featured: true,
    serviceSlug: "power-bi-dashboards",
    body: [
      {
        type: "p",
        text: "Sell-through rate answers one question: of everything we made available, how much has actually sold? It sounds trivial until two people in the same meeting quote different numbers — usually because one divides by units received and the other by units received plus opening stock.",
      },
      { type: "h2", id: "definition", text: "Sell-Through Rate Definition Used in Retail Reporting" },
      {
        type: "p",
        text: "Pick one definition per brand, write it down, and put it in the report description. The version below divides net sales units by total units made available in the period.",
      },
      { type: "formula", text: "sell-through % = net sales units ÷ (opening stock + received units)" },
      { type: "h2", id: "dax", text: "DAX Measures for Sell-Through Rate in Power BI" },
      {
        type: "p",
        text: "Three measures: net units, available units, and the ratio. Keeping them separate makes the number auditable — and lets you show both denominators side by side while the definition is being agreed.",
      },
      {
        type: "code",
        code: "Net Units :=\nSUM ( Sales[Units] ) - SUM ( Sales[ReturnUnits] )\n\nAvailable Units :=\nCALCULATE (\n    SUM ( Stock[OpeningUnits] ) + SUM ( Receipts[Units] ),\n    REMOVEFILTERS ( 'Date'[Week] )\n)\n\nSell-Through % :=\nDIVIDE ( [Net Units], [Available Units] )",
        caption: "Placeholder table and column names — rename to your model.",
      },
      { type: "h2", id: "weekly-curve", text: "Weekly Sell-Through Curve in a Retail Dashboard" },
      {
        type: "p",
        text: "A single percentage tells you little. The curve — cumulative sell-through by week, against last season — is what makes people act: too flat and the buy was too deep, too steep and you will be out of size before the season ends.",
      },
      {
        type: "chart",
        title: "Cumulative sell-through, weeks 1–12",
        legend: "this season vs last",
        caption: "placeholder data · solid = this season, dashed = last season",
      },
      {
        type: "table",
        caption: "placeholder data · select cells to see the average, count and sum below",
        columns: [
          { label: "Category", kind: "text" },
          { label: "Units received", kind: "number" },
          { label: "Sell-through, wk 8", kind: "number", format: "scale", suffix: "%" },
          { label: "Gross margin", kind: "number", format: "bars", suffix: "%" },
        ],
        trendColumn: 2,
        rows: [
          { cells: ["Dresses", 1240, 68, 42], trend: "up" },
          { cells: ["Knitwear", 980, 54, 38], trend: "flat" },
          { cells: ["Denim", 1510, 74, 47], trend: "up" },
          { cells: ["Outerwear", 640, 39, 31], trend: "down" },
          { cells: ["Accessories", 720, 61, 55], trend: "up" },
          { cells: ["Footwear", 560, 33, 29], trend: "down" },
        ],
      },
      { type: "h2", id: "mistakes", text: "Common Sell-Through Calculation Mistakes in Power BI" },
      {
        type: "list",
        items: [
          "Filtering the denominator by week, so availability resets every week and the curve looks flat.",
          "Leaving returns in sales units, which inflates sell-through in categories with high return rates.",
          "Mixing markets with different season start weeks in one cumulative view.",
        ],
      },
    ],
    seo: {
      title: "How to Calculate Sell-Through Rate in Power BI (DAX)",
      description: "Sell-through rate definition, DAX measures and a weekly sell-through curve for retail dashboards in Power BI.",
    },
  },
  {
    slug: "size-curve-from-sales-data",
    category: "assortment",
    title: "How to Build a Size Curve from Last Season’s Sales Data",
    h1: { before: "How to Build a Size Curve from", accent: "Last Season’s Sales Data" },
    excerpt: "Cleaning returns and stock-outs out of the data before you trust the size split.",
    lead: "Why raw sales make a misleading size curve, and the three cleaning steps that fix it.",
    date: "2026-05-12",
    readingMinutes: 7,
    cover: "tag",
    serviceSlug: "assortment-planning",
    body: [
      { type: "p", text: lorem("size curves") },
      { type: "h2", id: "why-raw-sales-mislead", text: "Why Raw Sales Data Gives a Wrong Size Curve" },
      { type: "p", text: lorem("stock-outs and returns in size data") },
      { type: "h2", id: "cleaning-steps", text: "Three Steps to Clean Sales Data Before Calculating a Size Curve" },
      { type: "list", items: ["Remove weeks where the size was out of stock.", "Use net sales after returns.", "Exclude promotion weeks with unusual demand."] },
      { type: "h2", id: "per-market", text: "Size Curves per Market and Category" },
      { type: "p", text: lorem("market-specific size curves") },
    ],
    seo: { title: "How to Build a Size Curve from Sales Data", description: "Clean returns, stock-outs and promotions out of sales history before calculating size curves for fashion retail." },
  },
  {
    slug: "product-attribute-standards-plm",
    category: "product-data",
    title: "Product Attribute Standards That Survive Three Markets",
    h1: { before: "Product Attribute Standards That Survive", accent: "Three Markets" },
    excerpt: "A practical attribute dictionary for PLM, with rules for colour, season and composition.",
    lead: "How to write an attribute dictionary that markets actually follow.",
    date: "2026-04-14",
    readingMinutes: 6,
    cover: "swatches",
    serviceSlug: "product-data-quality-plm",
    body: [
      { type: "p", text: lorem("attribute dictionaries") },
      { type: "h2", id: "colour", text: "Colour Attribute Rules in a PLM Dictionary" },
      { type: "p", text: lorem("colour attributes") },
      { type: "h2", id: "season", text: "Season Code Rules Across Markets" },
      { type: "p", text: lorem("season codes") },
      { type: "h2", id: "composition", text: "Composition Fields Without Free Text" },
      { type: "p", text: lorem("composition data") },
    ],
    seo: { title: "Product Attribute Standards for PLM Across Markets", description: "A practical PLM attribute dictionary with rules for colour, season and composition that work in several markets." },
  },
  {
    slug: "price-ladder-analysis",
    category: "pricing",
    title: "How to Read a Price Ladder Before Setting Next Season’s Prices",
    h1: { before: "How to Read a Price Ladder Before Setting", accent: "Next Season’s Prices" },
    excerpt: "Entry and exit points per category, and what a gap in the ladder actually costs.",
    lead: "A step-by-step way to check a price ladder against sales mix and margin.",
    date: "2026-03-10",
    readingMinutes: 6,
    cover: "table",
    serviceSlug: "retail-pricing-analysis",
    body: [
      { type: "p", text: lorem("price ladders") },
      { type: "h2", id: "tiers", text: "Entry, Core and Top Price Tiers per Category" },
      { type: "p", text: lorem("price tiers") },
      { type: "h2", id: "gaps", text: "What a Gap in the Price Ladder Costs" },
      { type: "p", text: lorem("price gaps") },
    ],
    seo: { title: "How to Read a Retail Price Ladder", description: "Check entry, core and top price tiers against sales mix and margin before setting next season's prices." },
  },
  {
    slug: "dax-measures-retail-kpi-dashboard",
    category: "power-bi",
    title: "Five DAX Measures Every Retail KPI Dashboard Needs",
    h1: { before: "Five DAX Measures Every", accent: "Retail KPI Dashboard", after: "Needs" },
    excerpt: "Stock cover, full-price share, returns rate, weeks of supply and contribution margin.",
    lead: "The five measures that turn a sales report into a retail trading dashboard.",
    date: "2026-02-09",
    readingMinutes: 9,
    cover: "lines",
    serviceSlug: "power-bi-dashboards",
    body: [
      { type: "p", text: lorem("retail KPI measures") },
      { type: "h2", id: "stock-cover", text: "Stock Cover Measure in DAX" },
      { type: "p", text: lorem("stock cover") },
      { type: "h2", id: "full-price-share", text: "Full-Price Sales Share Measure in DAX" },
      { type: "p", text: lorem("full-price share") },
      { type: "h2", id: "returns-rate", text: "Returns Rate Measure in DAX" },
      { type: "p", text: lorem("returns rate") },
    ],
    seo: { title: "Five DAX Measures for a Retail KPI Dashboard", description: "Stock cover, full-price share, returns rate, weeks of supply and contribution margin in DAX for retail dashboards." },
  },
  {
    slug: "open-to-buy-model-excel",
    category: "excel",
    title: "Building an Open-to-Buy Model in Excel That Planners Will Maintain",
    h1: { before: "Building an Open-to-Buy Model in Excel That", accent: "Planners Will Maintain" },
    excerpt: "Structure, phasing and the three checks that stop the model drifting mid-season.",
    lead: "How to structure an open-to-buy workbook so it survives the season and its author.",
    date: "2026-01-13",
    readingMinutes: 8,
    cover: "table",
    serviceSlug: "excel-retail-planning-models",
    body: [
      { type: "p", text: lorem("open-to-buy models") },
      { type: "h2", id: "structure", text: "Open-to-Buy Workbook Structure" },
      { type: "p", text: lorem("workbook structure") },
      { type: "h2", id: "checks", text: "Three Checks That Stop Open-to-Buy Drift" },
      { type: "list", items: ["Receipts match the purchase orders file.", "Sales match the latest export.", "Closing stock equals next month's opening stock."] },
    ],
    seo: { title: "Open-to-Buy Model in Excel for Retail Planners", description: "Structure, phasing and three checks for an open-to-buy Excel model that planners can maintain." },
  },
  {
    slug: "row-level-security-retail-reporting",
    category: "power-bi",
    title: "Row-Level Security in Power BI for Multi-Market Retail Reporting",
    h1: { before: "Row-Level Security in Power BI for", accent: "Multi-Market Retail Reporting" },
    excerpt: "One report, many markets: how to give each team its own numbers without copies.",
    lead: "How to set up row-level security so every market sees only its own data.",
    date: "2025-12-08",
    readingMinutes: 7,
    cover: "lines",
    serviceSlug: "power-bi-dashboards",
    body: [
      { type: "p", text: lorem("row-level security") },
      { type: "h2", id: "roles", text: "Market Roles in Power BI Row-Level Security" },
      { type: "p", text: lorem("security roles") },
    ],
    seo: { title: "Row-Level Security in Power BI for Retail", description: "Give each market its own numbers in one Power BI report with row-level security." },
  },
  {
    slug: "sell-through-vs-finance",
    category: "power-bi",
    title: "Why Your Sell-Through Chart Disagrees with Finance",
    h1: { before: "Why Your Sell-Through Chart", accent: "Disagrees with Finance" },
    excerpt: "Three definition mismatches that explain most reporting arguments in retail.",
    lead: "Three reasons why commercial and finance sell-through numbers differ, and how to agree one.",
    date: "2025-11-10",
    readingMinutes: 5,
    cover: "bars",
    serviceSlug: "power-bi-dashboards",
    body: [
      { type: "p", text: lorem("sell-through disagreements") },
      { type: "h2", id: "mismatches", text: "Three Sell-Through Definition Mismatches" },
      { type: "list", items: ["Units versus value.", "Gross versus net of returns.", "Period versus season-to-date availability."] },
    ],
    seo: { title: "Why Sell-Through Differs Between Commercial and Finance", description: "Three sell-through definition mismatches behind most retail reporting arguments." },
  },
];
