import type { CaseStudy } from "../../types";

/**
 * Anonymised, placeholder figures. Nothing here may be traceable to the
 * current employer: no market counts, internal project names or SKU counts.
 */
export const caseStudies: CaseStudy[] = [
  {
    slug: "plm-product-data-standardisation",
    topics: ["product-data"],
    tag: "Product data · PLM",
    title: "Standardising Product Data Across European and Asian Markets in a PLM System",
    h1: { before: "Standardising Product Data Across European and Asian Markets in a", accent: "PLM System" },
    summary: "Multi-market fashion brand. One attribute dictionary replaced many local conventions.",
    intro:
      "Local naming conventions replaced by one shared attribute dictionary, so the same product means the same thing in every market’s reporting.",
    cardMetrics: ["98% completeness", "−60% data fixes"],
    dashboard: "bars",
    breadcrumb: "Product data and PLM",
    facts: [
      { label: "Business", value: "multi-market fashion brand" },
      { label: "Markets", value: "Europe + Asia" },
      { label: "Scope", value: "full seasonal range" },
      { label: "Duration", value: "9 weeks" },
      { label: "Role", value: "lead analyst" },
    ],
    factsNote: "Anonymised client · placeholder figures",
    challengeTitle: "Product Data Challenge Across European and Asian Markets",
    challenge: [
      "Every market had grown its own way of describing product: colour written four ways, season codes that disagreed on when a season starts, compositions typed as free text.",
      "Consolidated reporting was therefore rebuilt by hand each month, and no one trusted a category total enough to act on it quickly.",
    ],
    challengePoints: [
      "Many local attribute conventions in one PLM instance",
      "~3 days of manual data cleaning per monthly report",
      "Category totals differing between markets and head office",
    ],
    actionsTitle: "What Was Done to Standardise the PLM Product Data",
    actions: [
      { label: "01", title: "Audit of existing product attributes per market", text: "Every field mapped, counted and scored for completeness and conflict." },
      { label: "02", title: "One attribute dictionary agreed with all markets", text: "Colour, season, composition and category defined once, with translations." },
      { label: "03", title: "Migration rules and PLM entry validation", text: "Historic data remapped; new products blocked at entry if key fields are missing." },
      { label: "04", title: "Data quality dashboard and monthly review", text: "Completeness per attribute and market, with a named owner for each gap." },
    ],
    resultsTitle: "Product Data Standardisation Results in Numbers",
    results: [
      { value: "98", unit: "%", label: "attribute completeness, from 71% at project start" },
      { value: "−60", unit: "%", label: "time spent fixing product data before reporting" },
      { value: "1", label: "attribute dictionary in place of many local conventions" },
      { value: "3", unit: "days", label: "of monthly manual cleaning removed from the reporting cycle" },
    ],
    toolsTitle: "Tools Used in the PLM Data Standardisation Project",
    tools: [
      { label: "PLM", title: "PLM system configuration", text: "Attribute lists, validation rules and market permissions." },
      { label: "fx", title: "Advanced Excel for mapping and migration", text: "Power Query pipelines for remapping historic attributes." },
      { label: "BI", title: "Power BI data quality dashboard", text: "Completeness by attribute, market and season, reviewed monthly." },
    ],
    serviceSlug: "product-data-quality-plm",
    serviceTitle: "Related Service: Product Data Quality and PLM Standardisation",
    serviceText:
      "The same method, adapted to your systems: audit, dictionary, migration rules, validation at entry and a quality dashboard your team reviews.",
    serviceChips: ["attribute dictionary", "migration rules", "data governance"],
    note: "The dictionary was the easy part — agreeing it was the project.",
    publishedAt: "2026-06-01",
    seo: {
      title: "Case Study: PLM Product Data Standardisation Across Markets",
      description:
        "How one attribute dictionary, PLM validation rules and a quality dashboard raised product data completeness to 98% for a multi-market fashion brand.",
    },
  },
  {
    slug: "womenswear-range-plan-rebuild",
    topics: ["assortment"],
    tag: "Assortment · Range",
    title: "Rebuilding the Womenswear Range Plan for a European Fashion Distributor",
    h1: { before: "Rebuilding the Womenswear Range Plan for a", accent: "European Fashion Distributor" },
    summary: "Option count cut by a fifth, depth moved into proven sizes and colours. Sell-through up, markdown down.",
    intro:
      "Option count cut by a fifth, depth moved into proven sizes and colours, monitored weekly through one Power BI model.",
    cardMetrics: ["+18 pp sell-through", "−31% markdown"],
    dashboard: "trend",
    breadcrumb: "Assortment planning",
    facts: [
      { label: "Business", value: "fashion distributor" },
      { label: "Category", value: "womenswear" },
      { label: "Duration", value: "8 weeks" },
      { label: "Role", value: "lead analyst" },
    ],
    factsNote: "Anonymised client · placeholder figures",
    challengeTitle: "Womenswear Range Planning Challenge",
    challenge: [
      "The range had grown season by season: more options every time, less depth behind each one. Stores ran out of core sizes early while fringe colours went to markdown.",
      "Size curves were copied from the previous plan, including the distortions caused by stock-outs.",
    ],
    challengePoints: [
      "Broken size runs by week four in core lines",
      "Markdown absorbing a growing share of margin",
      "No shared view of sell-through between buying and finance",
    ],
    actionsTitle: "What Was Done to Rebuild the Womenswear Range Plan",
    actions: [
      { label: "01", title: "Range architecture review by category and price tier", text: "Options compared with sell-through and margin history." },
      { label: "02", title: "Size and colour curves recalculated", text: "Returns, stock-outs and promo weeks removed from the history." },
      { label: "03", title: "New buy plan and open-to-buy model", text: "Depth moved into proven options, phasing by month." },
      { label: "04", title: "Weekly range monitoring in Power BI", text: "Sell-through and size integrity tracked against plan." },
    ],
    resultsTitle: "Womenswear Range Plan Results in Numbers",
    results: [
      { value: "+18", unit: "pp", label: "sell-through on core categories" },
      { value: "−21", unit: "%", label: "option count" },
      { value: "−31", unit: "%", label: "markdown spend across two seasons" },
    ],
    toolsTitle: "Tools Used in the Range Plan Project",
    tools: [
      { label: "fx", title: "Excel buy plan and open-to-buy", text: "Phasing and scenario comparison." },
      { label: "BI", title: "Power BI range monitoring", text: "Weekly sell-through and size integrity." },
    ],
    serviceSlug: "assortment-planning",
    serviceTitle: "Related Service: Assortment Planning and Range Management",
    serviceText: "Range architecture, size curves, buy plan and in-season monitoring, adapted to your categories and markets.",
    serviceChips: ["range architecture", "size curves", "open-to-buy"],
    note: "Fewer options, more depth — the hardest conversation was the first one.",
    publishedAt: "2026-05-01",
    seo: {
      title: "Case Study: Rebuilding a Womenswear Range Plan",
      description: "How a range architecture review, recalculated size curves and a new buy plan lifted sell-through by 18 pp for a fashion distributor.",
    },
  },
  {
    slug: "price-ladder-margin-report",
    topics: ["pricing", "reporting"],
    tag: "Pricing · Reporting",
    title: "Building a Price Ladder and Margin Report for a Fashion E-commerce Retailer",
    h1: { before: "Building a Price Ladder and Margin Report for a", accent: "Fashion E-commerce Retailer" },
    summary: "Entry and exit prices per category, aligned across three markets and monitored weekly in Power BI.",
    intro: "Entry and exit prices per category, aligned across markets and monitored weekly, so pricing decisions are made before margin is lost.",
    cardMetrics: ["+2.4 pp margin", "3 markets"],
    dashboard: "blocks",
    breadcrumb: "Retail pricing",
    facts: [
      { label: "Business", value: "fashion e-commerce retailer" },
      { label: "Markets", value: "3" },
      { label: "Duration", value: "6 weeks" },
      { label: "Role", value: "pricing analyst" },
    ],
    factsNote: "Anonymised client · placeholder figures",
    challengeTitle: "Retail Pricing Challenge in Fashion E-commerce",
    challenge: [
      "Prices were set per market with different rounding and currency logic, and the ladder had gaps that pushed customers to competitors.",
      "Margin was reviewed only at month end, too late to correct a promotion.",
    ],
    challengePoints: ["Overlapping price points in core categories", "Inconsistent prices between markets", "No weekly margin view"],
    actionsTitle: "What Was Done to Build the Price Ladder and Margin Report",
    actions: [
      { label: "01", title: "Price ladder audit", text: "Entry, core and top tiers per category." },
      { label: "02", title: "Cross-market pricing rules", text: "Conversion, rounding and allowed deviations." },
      { label: "03", title: "Weekly margin report in Power BI", text: "Price, discount and margin by category and market." },
    ],
    resultsTitle: "Price Ladder Project Results in Numbers",
    results: [
      { value: "+2.4", unit: "pp", label: "gross margin" },
      { value: "3", label: "markets on one set of pricing rules" },
      { value: "1", label: "weekly margin report" },
    ],
    toolsTitle: "Tools Used in the Pricing Project",
    tools: [
      { label: "fx", title: "Excel price scenarios", text: "Ladders and margin what-ifs." },
      { label: "BI", title: "Power BI margin report", text: "Weekly by category and market." },
    ],
    serviceSlug: "retail-pricing-analysis",
    serviceTitle: "Related Service: Retail Pricing Analysis",
    serviceText: "Price ladders, cross-market alignment and markdown scenarios for your categories.",
    serviceChips: ["price ladder", "margin", "markdown"],
    note: "A gap in the ladder is a price someone else sets for you.",
    publishedAt: "2026-04-01",
    seo: {
      title: "Case Study: Price Ladder and Margin Report for Fashion E-commerce",
      description: "How a price ladder audit and a weekly Power BI margin report added 2.4 pp gross margin for a fashion e-commerce retailer.",
    },
  },
  {
    slug: "weekly-retail-trade-report",
    topics: ["reporting"],
    tag: "Reporting · Process",
    title: "Setting Up a Weekly Retail Trade Report for a Multi-Brand Retailer",
    h1: { before: "Setting Up a Weekly Retail Trade Report for a", accent: "Multi-Brand Retailer" },
    summary: "One agreed definition set and a Monday report that replaced four competing spreadsheets.",
    intro: "One agreed definition set and a Monday report that replaced four competing spreadsheets.",
    cardMetrics: ["40 h/month saved", "4 → 1 report"],
    dashboard: "bars",
    breadcrumb: "Retail reporting",
    facts: [
      { label: "Business", value: "multi-brand retailer" },
      { label: "Audience", value: "buying, planning, finance" },
      { label: "Duration", value: "5 weeks" },
      { label: "Role", value: "analytics lead" },
    ],
    factsNote: "Anonymised client · placeholder figures",
    challengeTitle: "Weekly Retail Reporting Challenge",
    challenge: ["Four teams produced four weekly spreadsheets with different definitions of the same KPIs, and Monday meetings started with reconciliation."],
    challengePoints: ["Four competing weekly reports", "No written KPI definitions", "Two days of manual preparation every week"],
    actionsTitle: "What Was Done to Set Up the Weekly Trade Report",
    actions: [
      { label: "01", title: "KPI definitions agreed", text: "One sheet, signed off by all teams." },
      { label: "02", title: "Power BI trade report", text: "Built around the Monday meeting agenda." },
      { label: "03", title: "Reporting calendar and owners", text: "Who prepares, checks and presents." },
    ],
    resultsTitle: "Weekly Trade Report Results in Numbers",
    results: [
      { value: "40", unit: "h", label: "saved per month" },
      { value: "4 → 1", label: "weekly report" },
      { value: "100", unit: "%", label: "KPIs with an owner" },
    ],
    toolsTitle: "Tools Used in the Reporting Project",
    tools: [
      { label: "BI", title: "Power BI trade report", text: "Weekly refresh and market views." },
      { label: "fx", title: "Excel definition sheet", text: "Formulas, sources and owners." },
    ],
    serviceSlug: "retail-analytics-processes",
    serviceTitle: "Related Service: Setting Up Retail Analytics Processes",
    serviceText: "Reporting calendar, ownership and definitions that make numbers agreed once and reused everywhere.",
    serviceChips: ["reporting calendar", "ownership", "definitions"],
    note: "The report got simpler once everyone agreed what it was for.",
    publishedAt: "2026-03-01",
    seo: {
      title: "Case Study: Weekly Retail Trade Report Setup",
      description: "How one set of KPI definitions and a Power BI trade report replaced four spreadsheets and saved 40 hours a month.",
    },
  },
  {
    slug: "menswear-size-curve-rebuild",
    topics: ["assortment"],
    tag: "Assortment · Size curves",
    title: "Rebuilding Size Curves for a Menswear Brand After Two Seasons of Stock-Outs",
    h1: { before: "Rebuilding Size Curves for a Menswear Brand After", accent: "Two Seasons of Stock-Outs" },
    summary: "Returns and stock-outs cleaned out of the history before the curves were recalculated per market.",
    intro: "Returns and stock-outs cleaned out of the history before the curves were recalculated per market.",
    cardMetrics: ["−27% broken sizes", "+9 pp full-price"],
    dashboard: "trend",
    breadcrumb: "Size curves",
    facts: [
      { label: "Business", value: "menswear brand" },
      { label: "Duration", value: "4 weeks" },
      { label: "Role", value: "assortment analyst" },
    ],
    factsNote: "Anonymised client · placeholder figures",
    challengeTitle: "Menswear Size Curve Challenge",
    challenge: ["Two seasons of stock-outs had taught the size curves the wrong lesson: sizes that sold out looked unpopular in the data."],
    challengePoints: ["Stock-outs recorded as low demand", "Returns counted as sales", "One curve for all markets"],
    actionsTitle: "What Was Done to Rebuild the Size Curves",
    actions: [
      { label: "01", title: "Sales history cleaned", text: "Stock-out weeks and returns removed." },
      { label: "02", title: "Curves recalculated per market", text: "By category and fit." },
      { label: "03", title: "Size integrity monitoring", text: "Weekly check of broken size runs." },
    ],
    resultsTitle: "Size Curve Project Results in Numbers",
    results: [
      { value: "−27", unit: "%", label: "broken size runs" },
      { value: "+9", unit: "pp", label: "full-price share" },
    ],
    toolsTitle: "Tools Used in the Size Curve Project",
    tools: [
      { label: "fx", title: "Excel curve model", text: "Cleaned history and curves per market." },
      { label: "BI", title: "Power BI size integrity view", text: "Weekly monitoring." },
    ],
    serviceSlug: "assortment-planning",
    serviceTitle: "Related Service: Assortment Planning and Range Management",
    serviceText: "Size and colour curves calculated from cleaned history, per market.",
    serviceChips: ["size curves", "stock-outs", "returns"],
    note: "A sold-out size is not an unpopular size.",
    publishedAt: "2026-02-01",
    seo: {
      title: "Case Study: Menswear Size Curve Rebuild",
      description: "How cleaning stock-outs and returns from sales history cut broken size runs by 27% for a menswear brand.",
    },
  },
  {
    slug: "ecommerce-catalogue-attribute-cleaning",
    topics: ["product-data"],
    tag: "Product data · E-commerce",
    title: "Cleaning Product Attributes for a Fashion E-commerce Catalogue Migration",
    h1: { before: "Cleaning Product Attributes for a Fashion", accent: "E-commerce Catalogue Migration" },
    summary: "Attribute mapping and validation rules agreed before migration, so filters worked on day one.",
    intro: "Attribute mapping and validation rules agreed before migration, so filters worked on day one.",
    cardMetrics: ["99% mapped", "0 blocked SKUs"],
    dashboard: "blocks",
    breadcrumb: "Product data",
    facts: [
      { label: "Business", value: "fashion e-commerce" },
      { label: "Duration", value: "5 weeks" },
      { label: "Role", value: "product data analyst" },
    ],
    factsNote: "Anonymised client · placeholder figures",
    challengeTitle: "Catalogue Migration Data Challenge",
    challenge: ["A new e-commerce platform needed structured attributes for filters, while the old catalogue held most of them as free text."],
    challengePoints: ["Free-text colours and materials", "Missing categories", "Tight migration deadline"],
    actionsTitle: "What Was Done Before the Catalogue Migration",
    actions: [
      { label: "01", title: "Attribute mapping", text: "Old values mapped to the new structure." },
      { label: "02", title: "Validation rules", text: "Blocking checks before import." },
      { label: "03", title: "Exception list", text: "Manual review of the remaining cases." },
    ],
    resultsTitle: "Catalogue Migration Results in Numbers",
    results: [
      { value: "99", unit: "%", label: "attributes mapped" },
      { value: "0", label: "SKUs blocked at go-live" },
    ],
    toolsTitle: "Tools Used in the Migration Project",
    tools: [
      { label: "PQ", title: "Power Query mapping", text: "Repeatable remapping of attribute values." },
      { label: "fx", title: "Excel exception lists", text: "Owner and status per case." },
    ],
    serviceSlug: "product-data-quality-plm",
    serviceTitle: "Related Service: Product Data Quality and PLM Standardisation",
    serviceText: "Attribute dictionaries, mapping and validation rules for product data in PLM and e-commerce.",
    serviceChips: ["attribute mapping", "validation", "e-commerce"],
    note: "Filters only work if the data under them agrees.",
    publishedAt: "2026-01-01",
    seo: {
      title: "Case Study: Fashion E-commerce Catalogue Attribute Cleaning",
      description: "How attribute mapping and validation rules made 99% of product attributes ready for a fashion e-commerce migration.",
    },
  },
];
