import type { SiteContent } from "../../types";
import { formats, recommendations, services, tools } from "./services";
import { caseStudies } from "./caseStudies";
import { categories, posts } from "./blog";

const placeholderRec = (topic: string) => ({
  quote: `“Placeholder recommendation text. Two or three sentences from a colleague on ${topic}, quoted with permission once the real recommendation is in place.”`,
  name: "Name Surname",
  role: `Role · ${topic}`,
  placeholder: true,
});

const timeline = [
  {
    period: "2014 — 2016",
    company: "OMA",
    role: "Commercial analyst",
    text: "Sales reporting and planning support at a building materials retailer.",
  },
  {
    period: "2016 — 2018",
    company: "Luxvisage",
    role: "Category & pricing analyst",
    text: "Assortment and price structure for distributed product ranges.",
  },
  {
    period: "2018 — 2021",
    company: "Fashion House",
    role: "Retail analyst",
    text: "Multi-brand retail reporting, sell-through and tenant performance analysis.",
  },
  {
    period: "2021 — today",
    company: "International fashion brand",
    role: "Global Brand Analyst & Product Data Lead",
    text: "Assortment, pricing and product data across European and Asian markets.",
    current: true,
  },
];

export const en: SiteContent = {
  locale: "en",
  ui: {
    nav: [
      { label: "Services", href: "/services" },
      { label: "Case Studies", href: "/case-studies" },
      { label: "About", href: "/about" },
      { label: "Blog", href: "/blog" },
      { label: "Contact", href: "/contact" },
    ],
    tagline: "Retail & Fashion Analytics",
    bookConsultation: "Book a Consultation",
    menu: "Menu",
    close: "Close",
    switchLanguage: "Language",
    breadcrumbHome: "Home",
    footerText: "Assortment, pricing and Power BI reporting for fashion and retail brands. Based in Warsaw, working in EN, PL and RU.",
    footerServices: "Services",
    footerSite: "Site",
    footerContact: "Contact",
    footerSiteLinks: [
      { label: "Case studies", href: "/case-studies" },
      { label: "About", href: "/about" },
      { label: "Blog", href: "/blog" },
      { label: "Free templates", href: "/free-templates" },
      { label: "Courses", href: "/courses" },
      { label: "Contact", href: "/contact" },
    ],
    privacy: "Privacy policy",
    allCaseStudies: "All case studies",
    allArticles: "All articles",
    readArticle: "Read the article",
    featured: "Featured",
    minRead: "min read",
    seeCaseStudy: "See the related case study",
    relatedCaseStudy: "Related Case Study",
    relatedService: "Related service",
    relatedArticles: "Related Retail Analytics Articles",
    toc: "Table of contents",
    aboutLink: "About Tatsiana Bandziuk",
    replyNote: "Reply within two working days · EN / PL / RU",
    placeholderFigures: "placeholder figures",
    schematicCaption: "schematic dashboard · placeholder data",
    dashboardCaption: "anonymised dashboard illustration · schematic, placeholder data",
    portraitPlaceholder: "Portrait — to be replaced",
    recommendationPlaceholder: "Placeholder — real LinkedIn recommendations will be added with permission",
    allFilter: "All case studies",
    topics: { assortment: "Assortment", pricing: "Pricing", "product-data": "Product data", reporting: "Reporting" },
    slicer: { slicer: "Topic", clear: "Clear", chart: "Case studies by topic" },
    statusBar: { ready: "Ready", average: "Average", count: "Count", sum: "Sum", words: "Words", characters: "Characters", value: "Value" },
    pagination: { prev: "← Previous", next: "Next →", page: "Page" },
    form: {
      name: "Name",
      company: "Company",
      email: "Email",
      task: "Task or question",
      taskPlaceholder: "e.g. our range plan for SS27 and the markdown level",
      timeline: "Timeline / budget · optional",
      language: "Preferred language",
      submit: "Book a Consultation",
      sending: "Sending…",
      privacyNote: "Your data is used only to answer your enquiry.",
      required: "Please fill in this field.",
      invalidEmail: "Please enter a valid email address.",
      error: "The message could not be sent. Please write to hello@tatsianabandziuk.com.",
      workEmail: "Work email",
      emailPlaceholder: "name@company.com",
      phoneRequired: "Phone number",
      phoneOptional: "Phone · optional",
      invalidPhone: "Please enter a phone number with the country code, e.g. +48 600 000 000.",
      channelLegend: "How would you prefer to be contacted?",
      channelShort: "Preferred contact",
      channels: { email: "Email", whatsapp: "WhatsApp", phone: "Phone call" },
    },
    languages: { en: "English", pl: "Polski", ru: "Русский" },
    cookie: {
      title: "Cookies on this site",
      text: "Necessary cookies keep the site working. Analytics cookies, which show how visitors use the site, are set only if you agree.",
      accept: "Accept all",
      reject: "Only necessary",
      policy: "Privacy policy",
    },
  },
  person: {
    name: "Tatsiana Bandziuk",
    jobTitle: "Retail & fashion analytics consultant",
    shortBio:
      "Ten years in international fashion retail: assortment, pricing, product data and Power BI reporting. Based in Warsaw.",
    signature: "Tatsiana",
    email: "hello@tatsianabandziuk.com",
    location: "Warsaw",
    timezone: "CET",
    linkedin: "https://www.linkedin.com/in/tatsiana-bandziuk-a96b81165/",
    languages: [
      { label: "English", value: "professional" },
      { label: "Polski", value: "professional" },
      { label: "Русский", value: "native" },
    ],
    educationChip: "Master's in Economics, BSEU",
  },
  home: {
    seo: {
      title: "Tatsiana Bandziuk — Retail and Fashion Analytics Consultant",
      description:
        "Assortment planning, retail pricing analysis and Power BI reporting for fashion and retail brands. Consultant in Warsaw working in English, Polish and Russian.",
    },
    eyebrow: "Warsaw, Poland · EN / PL / RU",
    h1: { before: "Tatsiana Bandziuk,", accent: "Retail and Fashion Analytics", after: "Consultant" },
    subtitle: "Assortment, pricing and Power BI reporting for fashion and retail brands.",
    primaryCta: "Book a Consultation",
    secondaryCta: "See retail analytics case studies",
    stats: [
      { value: "10+", label: "years in fashion retail analytics" },
      { value: "30+", label: "dashboards and models delivered" },
      { value: "3", label: "working languages EN / PL / RU" },
    ],
    chartLabel: "Sell-through by week",
    chartDelta: "+18 pp",
    chartNote: "the week we fixed the size curve",
    experienceTitle: "Retail and Brand Analytics Experience at Luxvisage, Fashion House, OMA and an International Fashion Brand",
    experienceNames: ["Luxvisage", "Fashion House", "OMA", "International fashion brand"],
    servicesTitle: "Retail Analytics Consulting Services",
    servicesCount: "06 services",
    aboutTitle: "About Tatsiana Bandziuk, Retail and Fashion Analytics Consultant",
    aboutText: [
      "Placeholder text: ten years in international fashion retail, spent between commercial teams and the systems behind them — assortment, pricing, product data and the reporting that has to agree with all three.",
      "Placeholder text: today Global Brand Analyst and Product Data Lead at an international fashion brand, leading a team of product specialists, and consulting from Warsaw in English, Polish and Russian.",
    ],
    timelineLabel: "Career timeline · dates to be confirmed from CV",
    timeline,
    aboutLink: "About Tatsiana Bandziuk",
    resultsTitle: "Retail Analytics Results in Numbers",
    resultsNote: "placeholder figures",
    results: [
      { value: "+18", unit: "pp", label: "sell-through on core categories after range rebuild" },
      { value: "−31", unit: "%", label: "markdown spend across two seasons" },
      { value: "40", unit: "h", label: "monthly reporting time removed by one Power BI model" },
      { value: "98", unit: "%", label: "product attribute completeness in PLM after standardisation" },
    ],
    formatsTitle: "Retail Analytics Consulting Formats and Who They Are For",
    clientTypesLabel: "Client types",
    clientTypes: ["Fashion brands", "Distributors", "E-commerce retailers", "Growing brands without an analytics team"],
    processTitle: "How a Retail Analytics Consulting Project Works",
    process: [
      { label: "STEP 01", title: "Diagnostics of Assortment and Data", text: "Two weeks reading your sales, stock and product data, and naming exactly where the money leaks." },
      { label: "STEP 02", title: "Plan of Analytics Priorities", text: "A written plan: what changes in range, pricing, data and reporting, in which order, with owners." },
      { label: "STEP 03", title: "Implementation of Models and Dashboards", text: "Excel models, PLM attribute rules and Power BI reports built on your live data." },
      { label: "STEP 04", title: "Handover to the Team", text: "Documentation, definitions and training sessions so the process runs without me." },
    ],
    processPhotoLabel: "Working moment — to be replaced",
    processNote: "Most projects start with one honest look at the data.",
    toolsTitle: "Analytics Tools: Power BI, Excel and PLM Systems",
    educationTitle: "Education and Certifications in Economics and Retail Analytics",
    educationChips: ["Master's in Economics — Belarusian State Economic University", "Certification slot — Microsoft PL-300, if applicable"],
    caseStudiesTitle: "Retail and Fashion Analytics Case Studies",
    recommendationsTitle: "Recommendations from Fashion Retail Colleagues",
    recommendationsNote: "Placeholder — real LinkedIn recommendations will be added with permission",
    faqTitle: "Retail Analytics Consulting FAQ",
    faqLead: "Five questions clients ask before the first call.",
    faq: [
      {
        question: "How does a retail analytics consulting engagement start?",
        answer: "With a two-week diagnostic of your sales, stock and product data. You get a written findings memo and a prioritised plan before any build work is agreed.",
      },
      {
        question: "Which data do you need to build retail KPI dashboards?",
        answer: "Sales, stock, receipts and returns at SKU and week level, plus product attributes. Exports from your ERP or PLM are enough to start.",
      },
      {
        question: "How long does an assortment and pricing project take?",
        answer: "Usually six to ten weeks, depending on the number of categories and markets.",
      },
      {
        question: "Do you work with small brands and distributors?",
        answer: "Yes. Smaller teams often gain the most, because one clear model replaces several manual files.",
      },
      {
        question: "In which languages and time zones do you consult?",
        answer: "English, Polish and Russian, from Warsaw on CET, with remote work across Europe and beyond.",
      },
    ],
    blogTitle: "Retail Analytics Blog Articles",
    contactTitle: "Contact Tatsiana Bandziuk about a Retail Analytics Project",
    contactNote:
      "Placeholder note: I read every enquiry myself. Tell me what is not working — the range, the prices, the product data or the reporting — and I will reply with the first questions I would ask. If it is not my kind of project, I will say so.",
  },
  about: {
    seo: {
      title: "About Tatsiana Bandziuk — Retail and Fashion Analytics Consultant",
      description:
        "Ten years in international fashion retail: assortment, pricing, product data and Power BI reporting. Education, experience and working languages.",
    },
    h1: { before: "About Tatsiana Bandziuk,", accent: "Retail and Fashion Analytics", after: "Consultant" },
    intro:
      "Ten years inside international fashion retail — assortment, pricing, product data and the reporting that holds them together. Now consulting from Warsaw for brands, distributors and e-commerce retailers.",
    chips: ["Assortment planning", "Retail pricing", "Power BI", "PLM product data", "Team leadership"],
    experienceTitle: "Global Brand Analyst and Product Data Lead Experience in International Fashion Retail",
    experienceText: [
      "Currently Global Brand Analyst and Product Data Lead at an international fashion brand, working across European and Asian markets on assortment performance, pricing structure and the product data that feeds both.",
      "The work sits between commercial and systems: agreeing what a number means, making the data produce it reliably, and getting buyers, planners and finance to use the same version.",
    ],
    projectsTitle: "Assortment, Pricing and Product Data Projects",
    projects: [
      { title: "Assortment and range performance analysis", text: "Option counts, size and colour curves, category depth and phasing across markets." },
      { title: "Pricing structure and markdown analysis", text: "Price ladders per category, entry and exit points, margin and markdown scenarios." },
      { title: "Product data standardisation in PLM systems", text: "Attribute dictionaries, season and colour structures, and governance rules that hold at data entry." },
      { title: "Retail KPI reporting in Power BI", text: "One model per brand for sell-through, stock cover, full-price share and returns." },
    ],
    leadershipTitle: "Leading Product Specialist and Analytics Teams",
    leadershipText: [
      "Leads a team of product specialists: setting data standards, reviewing quality, and building the habit of checking a number before it travels into a decision.",
      "In consulting projects this translates into handover that actually holds — documented definitions, named owners, and training sessions for the people who will run the reporting next season.",
    ],
    leadershipNote: "A report nobody owns stops being true within a month.",
    timelineTitle: "Career Timeline in Fashion Retail Analytics",
    timelineNote: "Dates to be confirmed from CV",
    timeline: [...timeline].reverse(),
    educationTitle: "Economics and Marketing Education at Belarusian State Economic University",
    educationText:
      "Master's degree in Economics, Belarusian State Economic University, Minsk — with marketing specialisation. The training shows up as a habit: define the question, then choose the metric.",
    educationChips: ["MSc Economics", "Marketing", "Minsk"],
    languagesTitle: "Working Languages and Location in Warsaw",
    languagesText:
      "Based in Warsaw, working remotely across Europe and beyond, on CET. Workshops, documentation and reporting delivered in any of three languages.",
    recommendationTitle: "Recommendation from a Fashion Retail Colleague on Analytics Leadership",
    recommendation: placeholderRec("leading product data and analytics work"),
    ctaTitle: "Discuss a Retail Analytics Project with Tatsiana Bandziuk",
    ctaText:
      "Placeholder note: describe the task in a few lines — range, pricing, product data or reporting — and I will reply with the first questions I would ask.",
    ctaNote: "Goes to the contact form · EN / PL / RU",
  },
  servicesPage: {
    seo: {
      title: "Retail and Fashion Analytics Consulting Services",
      description:
        "Assortment planning, retail pricing analysis, Power BI dashboards, Excel planning models, PLM product data and analytics process setup for fashion brands.",
    },
    eyebrow: "Services",
    h1: "Retail and Fashion Analytics Consulting Services",
    intro: "Six services, one method: read the data first, agree the definitions, then build something the team can keep running.",
    ctaTitle: "Discuss Which Retail Analytics Service Fits Your Brand",
    ctaText:
      "Placeholder note: tell me where the reporting hurts most and I will say which of the six is the right starting point — or that none of them is.",
    recommendationTitle: "Recommendation from a Fashion Retail Colleague on Retail Analytics Work",
    recommendation: placeholderRec("a retail analytics consulting project"),
  },
  services,
  formats,
  tools,
  recommendations,
  caseStudiesPage: {
    seo: {
      title: "Retail and Fashion Analytics Case Studies",
      description: "Anonymised assortment, pricing, product data and reporting projects in fashion retail, with the numbers that changed.",
    },
    eyebrow: "Case studies",
    h1: "Retail and Fashion Analytics Case Studies",
    intro: "Anonymised projects in assortment, pricing, product data and reporting, with the numbers that changed. All figures are placeholders.",
    ctaTitle: "Discuss a Retail Analytics Case Like These",
    ctaText: "Placeholder note: if one of these looks like your situation, send me the two or three sentences that describe yours.",
  },
  caseStudies,
  blogPage: {
    seo: {
      title: "Retail Analytics Blog: Power BI, Excel and Assortment Planning",
      description: "Practical articles on Power BI, Excel, assortment planning, pricing and product data for fashion retail analysts.",
    },
    eyebrow: "Blog",
    h1: "Retail Analytics Blog: Power BI, Excel and Assortment Planning",
    intro: "Practical notes from fashion retail analytics — measures, models and the definitions that stop two people quoting different numbers.",
  },
  categories,
  posts,
  contact: {
    seo: {
      title: "Contact Tatsiana Bandziuk — Retail Analytics Consulting",
      description: "Describe your assortment, pricing, product data or reporting task. Reply within two working days in English, Polish or Russian.",
    },
    eyebrow: "Contact",
    h1: "Contact Tatsiana Bandziuk about a Retail Analytics Consulting Project",
    intro: "Describe the task in a few lines. You will get a reply within two working days with the first questions and a suggested starting point.",
    note: "Placeholder note: I read every enquiry myself. Tell me what is not working — the range, the prices, the product data or the reporting — and I will reply with the first questions I would ask.",
    stepsTitle: "What Happens After You Write about a Retail Analytics Project",
    steps: [
      { label: "STEP 01", title: "Reply with first questions", text: "Within two working days: what I would need to see in the data and what I think the real question is." },
      { label: "STEP 02", title: "Short call in English, Polish or Russian", text: "Thirty minutes to check the problem is the one you described — and that I am the right person for it." },
      { label: "STEP 03", title: "Written scope and starting point", text: "A short proposal: format, duration, deliverables and what your team keeps afterwards." },
    ],
    languagesTitle: "Working Languages, Location and Time Zone",
    details: [
      { label: "English", value: "professional" },
      { label: "Polski", value: "professional" },
      { label: "Русский", value: "native" },
      { label: "Warsaw", value: "CET / CEST" },
      { label: "Remote work", value: "Europe and beyond" },
    ],
    faqTitle: "Questions about Contacting a Retail Analytics Consultant",
    faq: [
      { question: "How quickly do you reply to a project enquiry?", answer: "Within two working days, with first questions rather than a generic brochure." },
      { question: "Do you sign an NDA before seeing retail data?", answer: "Yes. An NDA can be signed before any data is shared." },
      { question: "Can we start with a short call instead of a written brief?", answer: "Yes. A thirty-minute call is often the fastest way to see whether the project is a fit." },
    ],
  },
  courses: {
    seo: {
      title: "Power BI and Excel Courses for Retail and Fashion Analysts",
      description: "Practical Power BI and Excel courses for retail and fashion analysts, in preparation. Join the waitlist.",
    },
    eyebrow: "Courses · coming soon",
    h1: "Power BI and Excel Courses for Retail and Fashion Analysts",
    intro: "In preparation: short, practical courses built from real retail reporting problems, not from generic BI demos. Join the waitlist to hear first.",
    modulesTitle: "What the Retail Analytics Courses Will Cover",
    modules: [
      { label: "MODULE 01", title: "Power BI for Retail KPI Reporting", text: "Data model, DAX measures for sell-through and stock cover, and a dashboard structure a commercial team will open." },
      { label: "MODULE 02", title: "Excel Models for Assortment and Buy Planning", text: "Open-to-buy, phasing and scenarios, built so planners can maintain them without the author." },
      { label: "MODULE 03", title: "Pricing and Markdown Analysis in Practice", text: "Price ladders, margin scenarios and how to test a markdown plan before committing to it." },
      { label: "MODULE 04", title: "Product Data and Attribute Standards", text: "Building an attribute dictionary and validation rules that survive several markets." },
    ],
    audienceTitle: "Who the Power BI and Excel Courses Are For",
    audience: [
      "Retail and fashion analysts who report on assortment, pricing or stock",
      "Buyers and planners who build their own Excel models",
      "Small brand teams without an in-house BI specialist",
      "Analysts moving into fashion retail from another industry",
    ],
    waitlistTitle: "Join the Retail Analytics Course Waitlist",
    waitlistText: "Placeholder: one email when the first course opens, plus the free templates in the meantime. No newsletter.",
    waitlistButton: "Join the waitlist",
    meanwhile: "Meanwhile:",
    meanwhileLink: "free open-to-buy Excel template and retail KPI dashboard checklist",
  },
  templates: {
    seo: {
      title: "Free Open-to-Buy Excel Template and Retail KPI Dashboard Checklist",
      description: "Download a free open-to-buy Excel template and a retail KPI dashboard checklist for Power BI.",
    },
    eyebrow: "Free templates",
    h1: "Free Open-to-Buy Excel Template and Retail KPI Dashboard Checklist",
    intro: "Two working files from real retail projects, sent by email. Placeholder content until the final versions are uploaded.",
    items: [
      {
        title: "Open-to-Buy Excel Template for Retail Planning",
        text: "Units, cost, margin and phasing by month and market, with the three checks that stop the model drifting mid-season.",
        preview: "otb",
        previewCaption: "preview · open-to-buy sheet",
      },
      {
        title: "Retail KPI Dashboard Checklist for Power BI",
        text: "Twelve checks before a retail dashboard goes to the commercial team — definitions, owners and refresh.",
        preview: "checklist",
        previewCaption: "preview · dashboard checklist",
      },
    ],
    checklist: [
      "Sell-through defined and documented",
      "Stock cover per category and market",
      "Full-price share and markdown depth",
      "Returns rate in the same model",
      "One owner per report page",
    ],
    insideTitle: "What Is Inside the Retail Analytics Templates",
    inside: [
      "Open-to-buy sheet with monthly phasing and margin calculation",
      "Size and colour curve tab fed from cleaned sales history",
      "Definition sheet: how each retail KPI is calculated and by whom",
      "Dashboard checklist with the twelve pre-launch checks",
      "A one-page note on handing the model to a planning team",
    ],
    formTitle: "Get Both Retail Analytics Templates by Email",
    formText: "One email with both files. No newsletter, no sharing of your address.",
    panelTitle: "Free Retail Analytics Templates for Excel and Power BI",
    panelText:
      "Placeholder: two downloads sent by email — an open-to-buy planning model and a checklist for a retail KPI dashboard that a commercial team will actually open.",
    chips: ["Open-to-Buy Excel Template", "Retail KPI Dashboard Checklist"],
    button: "Send me both templates",
    courseNote: "Power BI and Excel courses for retail analysts — coming soon. No newsletter, no sharing of your address.",
    relatedTitle: "Related Retail Analytics Articles",
  },
  privacy: {
    seo: {
      title: "Privacy Policy for tatsianabandziuk.com",
      description: "How personal data from the contact form, the free templates and the course waitlist is handled on tatsianabandziuk.com.",
    },
    slug: "privacy-policy",
    eyebrow: "Legal · last updated 2026",
    h1: "Privacy Policy for tatsianabandziuk.com",
    intro: "How personal data from the contact form, the free templates and the course waitlist is handled. Placeholder text pending legal review.",
    sections: [
      { id: "controller", title: "1. Data Controller and Contact Details", text: "Placeholder text: the controller of personal data collected through tatsianabandziuk.com is Tatsiana Bandziuk, Warsaw, Poland. Questions about this policy can be sent to hello@tatsianabandziuk.com and are answered within two working days." },
      { id: "contact-form", title: "2. Personal Data Collected Through the Contact Form", text: "Placeholder text: name, company, email address, the description of your task and, optionally, timeline or budget. The data is used only to answer your enquiry and to prepare a proposal." },
      { id: "templates", title: "3. Personal Data Collected for Free Templates and the Course Waitlist", text: "Placeholder text: your email address, stored to send the files you requested and, for the waitlist, one message when a course opens. You can ask for removal at any time." },
      { id: "legal-basis", title: "4. Legal Basis and Retention Periods", text: "Placeholder text: legitimate interest for answering business enquiries and consent for the templates and waitlist. Enquiry data is kept for the duration of the conversation plus a placeholder retention period." },
      { id: "cookies", title: "5. Cookies and Website Analytics", text: "Placeholder text: the site uses cookies required for it to work and, only with your consent, analytics cookies (Google Analytics, Microsoft Clarity). A cookie table will be added here." },
      { id: "processors", title: "6. Data Processors and Third-Party Services", text: "Placeholder text: hosting, email delivery and analytics providers act as processors under contract. Their names and locations will be listed here." },
      { id: "rights", title: "7. Your Rights Under the GDPR", text: "Placeholder text: access, rectification, erasure, restriction, objection, portability and the right to lodge a complaint with the Polish supervisory authority." },
      { id: "changes", title: "8. Changes to This Privacy Policy", text: "Placeholder text: material changes will be announced on this page with a new effective date." },
    ],
    note: "Placeholder note: this text is a structural draft and must be reviewed by a lawyer before publication.",
  },
  notFound: {
    eyebrow: "Error 404",
    h1: "Page Not Found on tatsianabandziuk.com",
    text: "This URL has no data behind it. The chart on the right is what that looks like in a weekly report.",
    note: "Every dataset has one of these somewhere.",
    chartLabel: "Sessions on this page",
    nextTitle: "Where to Go Next on the Retail Analytics Site",
    links: [
      { title: "Retail Analytics Consulting Services", text: "six services and three formats", href: "/services" },
      { title: "Retail and Fashion Analytics Case Studies", text: "anonymised projects with numbers", href: "/case-studies" },
      { title: "Retail Analytics Blog Articles", text: "Power BI, Excel and assortment", href: "/blog" },
      { title: "Contact about a Retail Analytics Project", text: "reply within two working days", href: "/contact" },
    ],
  },
  thankYou: {
    contactTitle: "Thank You — Your Retail Analytics Enquiry Has Been Sent",
    contactText: "Placeholder text: I read every enquiry myself and reply within two working days, usually with two or three questions about your data before anything else.",
    nextTitle: "What Happens Next with Your Enquiry",
    next: [
      "Reply with first questions — within two working days",
      "Short call in English, Polish or Russian",
      "Written scope, duration and deliverables",
    ],
    caseStudiesLink: "Read the case studies",
    templatesLink: "Free templates",
    templatesTitle: "Check Your Inbox for the Open-to-Buy Template and Dashboard Checklist",
    templatesText: "Placeholder text: both files are on their way. If nothing arrives within ten minutes, check spam or write to me directly.",
    sent: "SENT",
    whileYouWait: "While You Wait: Retail Analytics Articles",
    close: "Close and keep reading",
  },
};
