import type { SiteContent } from "../../types";
import { en } from "../en";
import { formats, recommendations, services, tools } from "./services";
import { caseStudies, categories, posts } from "./work";

const placeholderRec = (topic: string) => ({
  quote: `„Tekst zastępczy rekomendacji. Dwa lub trzy zdania od współpracownika o ${topic}, cytowane za zgodą, gdy pojawi się prawdziwa rekomendacja.”`,
  name: "Imię Nazwisko",
  role: `Stanowisko · ${topic}`,
  placeholder: true,
});

const timeline = [
  { period: "2014 — 2016", company: "OMA", role: "Analityczka handlowa", text: "Raportowanie sprzedaży i wsparcie planowania w sieci materiałów budowlanych." },
  { period: "2016 — 2018", company: "Luxvisage", role: "Analityczka kategorii i cen", text: "Struktura asortymentu i cen dla dystrybuowanych kolekcji." },
  { period: "2018 — 2021", company: "Fashion House", role: "Analityczka retail", text: "Raporty wielomarkowe, sell-through i wyniki najemców." },
  { period: "2021 — obecnie", company: "Międzynarodowa marka modowa", role: "Global Brand Analyst & Product Data Lead", text: "Asortyment, ceny i dane produktowe na rynkach Europy i Azji.", current: true },
];

export const pl: SiteContent = {
  locale: "pl",
  ui: {
    ...en.ui,
    nav: [
      { label: "Usługi", href: "/services" },
      { label: "Case studies", href: "/case-studies" },
      { label: "O mnie", href: "/about" },
      { label: "Blog", href: "/blog" },
      { label: "Kontakt", href: "/contact" },
    ],
    tagline: "Analityka w handlu i modzie",
    bookConsultation: "Umów konsultację",
    menu: "Menu",
    close: "Zamknij",
    switchLanguage: "Język",
    breadcrumbHome: "Strona główna",
    footerText: "Asortyment, ceny i raportowanie w Power BI dla marek modowych i sieci handlowych. Warszawa, praca w EN, PL i RU.",
    footerServices: "Usługi",
    footerSite: "Strona",
    footerContact: "Kontakt",
    footerSiteLinks: [
      { label: "Case studies", href: "/case-studies" },
      { label: "O mnie", href: "/about" },
      { label: "Blog", href: "/blog" },
      { label: "Darmowe szablony", href: "/free-templates" },
      { label: "Kursy", href: "/courses" },
      { label: "Kontakt", href: "/contact" },
    ],
    privacy: "Polityka prywatności",
    allCaseStudies: "Wszystkie case studies",
    allArticles: "Wszystkie artykuły",
    readArticle: "Przeczytaj artykuł",
    featured: "Polecany",
    minRead: "min czytania",
    seeCaseStudy: "Zobacz powiązane case study",
    relatedCaseStudy: "Powiązane case study",
    relatedService: "Powiązana usługa",
    relatedArticles: "Powiązane artykuły o analityce handlowej",
    toc: "Spis treści",
    aboutLink: "O Tatsianie Bandziuk",
    replyNote: "Odpowiedź w ciągu dwóch dni roboczych · EN / PL / RU",
    placeholderFigures: "dane zastępcze",
    schematicCaption: "schemat dashboardu · dane zastępcze",
    dashboardCaption: "zanonimizowana ilustracja dashboardu · dane zastępcze",
    portraitPlaceholder: "Portret — do podmiany",
    recommendationPlaceholder: "Zastępczo — prawdziwe rekomendacje z LinkedIn pojawią się za zgodą autorów",
    allFilter: "Wszystkie",
    topics: { assortment: "Asortyment", pricing: "Ceny", "product-data": "Dane produktowe", reporting: "Raportowanie" },
    slicer: { slicer: "Temat", clear: "Wyczyść", chart: "Studia przypadków według tematu" },
    statusBar: { ready: "Gotowy", average: "Średnia", count: "Licznik", sum: "Suma", words: "Słowa", characters: "Znaki", value: "Wartość" },
    pagination: { prev: "← Poprzednia", next: "Następna →", page: "Strona" },
    form: {
      name: "Imię i nazwisko",
      company: "Firma",
      email: "E-mail",
      task: "Zadanie lub pytanie",
      taskPlaceholder: "np. plan kolekcji na SS27 i poziom obniżek",
      timeline: "Termin / budżet · opcjonalnie",
      language: "Preferowany język",
      submit: "Umów konsultację",
      sending: "Wysyłanie…",
      privacyNote: "Dane wykorzystam wyłącznie do odpowiedzi na zapytanie.",
      required: "Uzupełnij to pole.",
      invalidEmail: "Podaj poprawny adres e-mail.",
      error: "Nie udało się wysłać wiadomości. Napisz na hello@tatsianabandziuk.com.",
      workEmail: "Służbowy e-mail",
      emailPlaceholder: "imie@firma.pl",
      phoneRequired: "Numer telefonu",
      phoneOptional: "Telefon · opcjonalnie",
      invalidPhone: "Podaj numer telefonu z kodem kraju, np. +48 600 000 000.",
      channelLegend: "Jaka forma kontaktu jest dla Ciebie wygodna?",
      channelShort: "Preferowany kontakt",
      channels: { email: "E-mail", whatsapp: "WhatsApp", phone: "Telefon" },
    },
    cookie: {
      title: "Pliki cookie na tej stronie",
      text: "Niezbędne pliki cookie zapewniają działanie strony. Analityczne pliki cookie ustawiamy tylko za Twoją zgodą.",
      accept: "Akceptuj wszystkie",
      reject: "Tylko niezbędne",
      policy: "Polityka prywatności",
    },
  },
  person: {
    ...en.person,
    jobTitle: "Konsultantka ds. analityki w handlu i modzie",
    shortBio: "Dziesięć lat w międzynarodowym handlu modą: asortyment, ceny, dane produktowe i raporty Power BI. Warszawa.",
    location: "Warszawa",
    languages: [
      { label: "English", value: "biegły" },
      { label: "Polski", value: "biegły" },
      { label: "Русский", value: "ojczysty" },
    ],
    educationChip: "Magister ekonomii, BSEU",
  },
  home: {
    ...en.home,
    seo: {
      title: "Tatsiana Bandziuk — konsultantka ds. analityki w handlu i modzie",
      description: "Planowanie asortymentu, analiza cen i raportowanie w Power BI dla marek modowych i sieci handlowych. Konsultantka w Warszawie, EN / PL / RU.",
    },
    eyebrow: "Warszawa · EN / PL / RU",
    h1: { before: "Tatsiana Bandziuk,", accent: "konsultantka analityki w handlu i modzie" },
    subtitle: "Asortyment, ceny i raportowanie w Power BI dla marek modowych i sieci handlowych.",
    primaryCta: "Umów konsultację",
    secondaryCta: "Zobacz case studies",
    stats: [
      { value: "10+", label: "lat w analityce handlu modą" },
      { value: "30+", label: "dashboardów i modeli" },
      { value: "3", label: "języki pracy EN / PL / RU" },
    ],
    chartLabel: "Sell-through tygodniowo",
    chartNote: "tydzień, w którym poprawiłyśmy krzywą rozmiarów",
    experienceTitle: "Doświadczenie w analityce handlu i marek: Luxvisage, Fashion House, OMA i międzynarodowa marka modowa",
    experienceNames: ["Luxvisage", "Fashion House", "OMA", "Międzynarodowa marka modowa"],
    servicesTitle: "Usługi doradcze w analityce handlowej",
    servicesCount: "06 usług",
    aboutTitle: "O Tatsianie Bandziuk, konsultantce ds. analityki w handlu i modzie",
    aboutText: [
      "Tekst zastępczy: dziesięć lat w międzynarodowym handlu modą — między zespołami handlowymi a systemami, na których pracują: asortyment, ceny, dane produktowe i raporty.",
      "Tekst zastępczy: obecnie Global Brand Analyst i Product Data Lead w międzynarodowej marce modowej, kieruje zespołem specjalistów produktowych i doradza z Warszawy po angielsku, polsku i rosyjsku.",
    ],
    timelineLabel: "Ścieżka zawodowa · daty do potwierdzenia z CV",
    timeline,
    aboutLink: "O Tatsianie Bandziuk",
    resultsTitle: "Wyniki analityki handlowej w liczbach",
    resultsNote: "dane zastępcze",
    results: [
      { value: "+18", unit: "pp", label: "sell-through w kluczowych kategoriach po przebudowie kolekcji" },
      { value: "−31", unit: "%", label: "kosztów obniżek w dwóch sezonach" },
      { value: "40", unit: "h", label: "miesięcznie mniej pracy nad raportami dzięki modelowi Power BI" },
      { value: "98", unit: "%", label: "kompletności atrybutów produktów w PLM" },
    ],
    formatsTitle: "Formy współpracy w doradztwie analitycznym i dla kogo są",
    clientTypesLabel: "Klienci",
    clientTypes: ["Marki modowe", "Dystrybutorzy", "Sklepy internetowe", "Rosnące marki bez zespołu analitycznego"],
    processTitle: "Jak przebiega projekt doradztwa w analityce handlowej",
    process: [
      { label: "KROK 01", title: "Diagnostyka asortymentu i danych", text: "Dwa tygodnie analizy sprzedaży, zapasów i danych produktowych oraz wskazanie, gdzie uciekają pieniądze." },
      { label: "KROK 02", title: "Plan priorytetów analitycznych", text: "Pisemny plan zmian w kolekcji, cenach, danych i raportach — kolejność i właściciele." },
      { label: "KROK 03", title: "Wdrożenie modeli i dashboardów", text: "Modele w Excelu, reguły atrybutów PLM i raporty Power BI na Twoich danych." },
      { label: "KROK 04", title: "Przekazanie zespołowi", text: "Dokumentacja, definicje i szkolenia, aby proces działał bez konsultanta." },
    ],
    processPhotoLabel: "Zdjęcie przy pracy — do podmiany",
    processNote: "Większość projektów zaczyna się od uczciwego spojrzenia na dane.",
    toolsTitle: "Narzędzia analityczne: Power BI, Excel i systemy PLM",
    educationTitle: "Wykształcenie i certyfikaty w ekonomii i analityce handlowej",
    educationChips: ["Magister ekonomii — Białoruski Państwowy Uniwersytet Ekonomiczny", "Miejsce na certyfikat — Microsoft PL-300, jeśli dotyczy"],
    caseStudiesTitle: "Case studies z analityki handlu i mody",
    recommendationsTitle: "Rekomendacje współpracowników z branży mody",
    recommendationsNote: "Zastępczo — prawdziwe rekomendacje z LinkedIn pojawią się za zgodą autorów",
    faqTitle: "Doradztwo w analityce handlowej — najczęstsze pytania",
    faqLead: "Pięć pytań, które klienci zadają przed pierwszą rozmową.",
    faq: [
      { question: "Jak zaczyna się współpraca w zakresie analityki handlowej?", answer: "Od dwutygodniowej diagnostyki sprzedaży, zapasów i danych produktowych. Otrzymujesz raport z ustaleniami i plan priorytetów." },
      { question: "Jakie dane są potrzebne do dashboardów KPI?", answer: "Sprzedaż, zapasy, dostawy i zwroty per SKU i tydzień oraz atrybuty produktów." },
      { question: "Ile trwa projekt asortymentowy lub cenowy?", answer: "Zwykle od sześciu do dziesięciu tygodni." },
      { question: "Czy pracujesz z małymi markami i dystrybutorami?", answer: "Tak, mniejsze zespoły często zyskują najwięcej." },
      { question: "W jakich językach i strefach czasowych doradzasz?", answer: "Po angielsku, polsku i rosyjsku, z Warszawy w strefie CET." },
    ],
    blogTitle: "Artykuły o analityce handlowej",
    contactTitle: "Napisz do Tatsiany Bandziuk w sprawie projektu analitycznego",
    contactNote: "Tekst zastępczy: każde zapytanie czytam osobiście. Napisz, co nie działa — kolekcja, ceny, dane produktowe czy raporty — a odpowiem pierwszymi pytaniami.",
  },
  about: {
    ...en.about,
    seo: {
      title: "O Tatsianie Bandziuk — konsultantka ds. analityki w handlu i modzie",
      description: "Dziesięć lat w międzynarodowym handlu modą: asortyment, ceny, dane produktowe i Power BI. Wykształcenie, doświadczenie i języki pracy.",
    },
    h1: { before: "O Tatsianie Bandziuk,", accent: "konsultantce analityki w handlu i modzie" },
    intro: "Dziesięć lat w międzynarodowym handlu modą — asortyment, ceny, dane produktowe i raporty, które to spinają. Obecnie doradza z Warszawy markom, dystrybutorom i sklepom internetowym.",
    chips: ["Planowanie asortymentu", "Ceny", "Power BI", "Dane produktowe PLM", "Kierowanie zespołem"],
    experienceTitle: "Doświadczenie Global Brand Analyst i Product Data Lead w międzynarodowym handlu modą",
    experienceText: [
      "Obecnie Global Brand Analyst i Product Data Lead w międzynarodowej marce modowej: wyniki asortymentu, struktura cen i dane produktowe na rynkach Europy i Azji.",
      "Praca na styku handlu i systemów: uzgodnić, co znaczy liczba, sprawić, by dane liczyły ją rzetelnie, i przekonać zakupy, planowanie oraz finanse do jednej wersji.",
    ],
    projectsTitle: "Projekty asortymentowe, cenowe i z danymi produktowymi",
    projects: [
      { title: "Analiza wyników asortymentu i kolekcji", text: "Liczba opcji, krzywe rozmiarów i kolorów, głębokość kategorii." },
      { title: "Analiza struktury cen i obniżek", text: "Drabinki cenowe, progi wejścia i wyjścia, scenariusze marży." },
      { title: "Standaryzacja danych produktowych w PLM", text: "Słowniki atrybutów, struktury sezonów i kolorów, reguły jakości." },
      { title: "Raportowanie KPI w Power BI", text: "Jeden model dla sell-through, zapasów, pełnej ceny i zwrotów." },
    ],
    leadershipTitle: "Kierowanie zespołami specjalistów produktowych i analityków",
    leadershipText: [
      "Kieruje zespołem specjalistów produktowych: standardy danych, kontrola jakości i nawyk sprawdzania liczby, zanim trafi do decyzji.",
      "W projektach doradczych oznacza to przekazanie, które naprawdę działa — definicje, właściciele i szkolenia.",
    ],
    leadershipNote: "Raport bez właściciela po miesiącu przestaje być prawdziwy.",
    timelineTitle: "Ścieżka zawodowa w analityce handlu modą",
    timelineNote: "Daty do potwierdzenia z CV",
    timeline: [...timeline].reverse(),
    educationTitle: "Wykształcenie ekonomiczne i marketingowe na Białoruskim Państwowym Uniwersytecie Ekonomicznym",
    educationText: "Magister ekonomii, Białoruski Państwowy Uniwersytet Ekonomiczny w Mińsku, specjalizacja marketingowa. Nawyk z tamtych lat: najpierw pytanie, potem miara.",
    educationChips: ["Magister ekonomii", "Marketing", "Mińsk"],
    languagesTitle: "Języki pracy i lokalizacja w Warszawie",
    languagesText: "Warszawa, praca na odległość w Europie i poza nią, strefa CET. Warsztaty, dokumentacja i raporty w jednym z trzech języków.",
    recommendationTitle: "Rekomendacja współpracownika z branży mody dotycząca kierowania analityką",
    recommendation: placeholderRec("kierowaniu pracą z danymi produktowymi"),
    ctaTitle: "Porozmawiaj z Tatsianą Bandziuk o projekcie analitycznym",
    ctaText: "Tekst zastępczy: opisz zadanie w kilku zdaniach — kolekcja, ceny, dane produktowe lub raporty — a odpowiem pierwszymi pytaniami.",
    ctaNote: "Prowadzi do formularza kontaktowego · EN / PL / RU",
  },
  servicesPage: {
    seo: { title: "Usługi doradcze w analityce handlu i mody", description: "Planowanie asortymentu, analiza cen, dashboardy Power BI, modele Excel, dane PLM i procesy analityczne dla marek modowych." },
    eyebrow: "Usługi",
    h1: "Usługi doradcze w analityce handlu i mody",
    intro: "Sześć usług, jedna metoda: najpierw dane, potem uzgodnione definicje, na końcu coś, co zespół potrafi dalej prowadzić.",
    ctaTitle: "Porozmawiajmy, która usługa analityczna pasuje do Twojej marki",
    ctaText: "Tekst zastępczy: napisz, gdzie raportowanie boli najbardziej, a wskażę właściwy punkt startu — albo powiem, że żaden z sześciu.",
    recommendationTitle: "Rekomendacja współpracownika z branży mody dotycząca analityki handlowej",
    recommendation: placeholderRec("projekcie doradczym"),
  },
  services,
  formats,
  tools,
  recommendations,
  caseStudiesPage: {
    seo: { title: "Case studies z analityki handlu i mody", description: "Zanonimizowane projekty z asortymentu, cen, danych produktowych i raportowania w handlu modą." },
    eyebrow: "Case studies",
    h1: "Case studies z analityki handlu i mody",
    intro: "Zanonimizowane projekty z asortymentu, cen, danych produktowych i raportowania, z liczbami, które się zmieniły. Wszystkie dane są zastępcze.",
    ctaTitle: "Porozmawiajmy o podobnym projekcie analitycznym",
    ctaText: "Tekst zastępczy: jeśli któryś przypadek przypomina Twoją sytuację, opisz ją w dwóch–trzech zdaniach.",
  },
  caseStudies,
  blogPage: {
    seo: { title: "Blog o analityce handlowej: Power BI, Excel i planowanie asortymentu", description: "Praktyczne artykuły o Power BI, Excelu, asortymencie, cenach i danych produktowych w handlu modą." },
    eyebrow: "Blog",
    h1: "Blog o analityce handlowej: Power BI, Excel i planowanie asortymentu",
    intro: "Praktyczne notatki z analityki handlu modą — miary, modele i definicje, dzięki którym dwie osoby podają tę samą liczbę.",
  },
  categories,
  posts,
  contact: {
    seo: { title: "Kontakt — doradztwo w analityce handlowej", description: "Opisz zadanie z asortymentu, cen, danych produktowych lub raportowania. Odpowiedź w ciągu dwóch dni roboczych." },
    eyebrow: "Kontakt",
    h1: "Napisz do Tatsiany Bandziuk w sprawie projektu doradztwa analitycznego",
    intro: "Opisz zadanie w kilku zdaniach. W ciągu dwóch dni roboczych otrzymasz pierwsze pytania i propozycję punktu startu.",
    note: "Tekst zastępczy: każde zapytanie czytam osobiście. Napisz, co nie działa — a odpowiem pierwszymi pytaniami, które bym zadała.",
    stepsTitle: "Co dzieje się po wysłaniu zapytania o projekt analityczny",
    steps: [
      { label: "KROK 01", title: "Odpowiedź z pierwszymi pytaniami", text: "W ciągu dwóch dni roboczych: jakie dane chciałabym zobaczyć i jakie jest prawdziwe pytanie." },
      { label: "KROK 02", title: "Krótka rozmowa po angielsku, polsku lub rosyjsku", text: "Trzydzieści minut, by potwierdzić problem i dopasowanie." },
      { label: "KROK 03", title: "Pisemny zakres i punkt startu", text: "Krótka oferta: forma, czas trwania, rezultaty i to, co zostaje w zespole." },
    ],
    languagesTitle: "Języki pracy, lokalizacja i strefa czasowa",
    details: [
      { label: "English", value: "biegły" },
      { label: "Polski", value: "biegły" },
      { label: "Русский", value: "ojczysty" },
      { label: "Warszawa", value: "CET / CEST" },
      { label: "Praca na odległość", value: "Europa i nie tylko" },
    ],
    faqTitle: "Pytania o kontakt z konsultantką ds. analityki handlowej",
    faq: [
      { question: "Jak szybko odpowiadasz na zapytanie o projekt?", answer: "W ciągu dwóch dni roboczych, z konkretnymi pytaniami." },
      { question: "Czy podpisujesz NDA przed udostępnieniem danych?", answer: "Tak, NDA można podpisać przed przekazaniem danych." },
      { question: "Czy możemy zacząć od krótkiej rozmowy zamiast briefu?", answer: "Tak, trzydziestominutowa rozmowa to często najszybsza droga." },
    ],
  },
  courses: {
    ...en.courses,
    seo: { title: "Kursy Power BI i Excel dla analityków handlu i mody", description: "Praktyczne kursy Power BI i Excel dla analityków w handlu modą — w przygotowaniu. Zapisz się na listę." },
    eyebrow: "Kursy · wkrótce",
    h1: "Kursy Power BI i Excel dla analityków handlu i mody",
    intro: "W przygotowaniu: krótkie, praktyczne kursy oparte na prawdziwych problemach raportowych w handlu. Zapisz się, aby dowiedzieć się pierwsza/y.",
    modulesTitle: "Czego nauczą kursy analityki handlowej",
    modules: [
      { label: "MODUŁ 01", title: "Power BI w raportowaniu KPI handlu", text: "Model danych, miary DAX dla sell-through i zapasów oraz struktura dashboardu." },
      { label: "MODUŁ 02", title: "Modele Excel do planowania asortymentu i zakupów", text: "Open-to-buy, rozłożenie w czasie i scenariusze." },
      { label: "MODUŁ 03", title: "Analiza cen i obniżek w praktyce", text: "Drabinki cenowe, scenariusze marży i test planu obniżek." },
      { label: "MODUŁ 04", title: "Dane produktowe i standardy atrybutów", text: "Słownik atrybutów i reguły walidacji dla wielu rynków." },
    ],
    audienceTitle: "Dla kogo są kursy Power BI i Excel",
    audience: [
      "Analitycy handlu i mody raportujący asortyment, ceny lub zapasy",
      "Kupcy i planiści budujący własne modele w Excelu",
      "Małe zespoły marek bez specjalisty BI",
      "Analitycy przechodzący do handlu modą z innych branż",
    ],
    waitlistTitle: "Zapisz się na listę oczekujących na kurs analityki handlowej",
    waitlistText: "Tekst zastępczy: jeden e-mail, gdy ruszy pierwszy kurs, a w międzyczasie darmowe szablony. Bez newslettera.",
    waitlistButton: "Zapisz mnie",
    meanwhile: "W międzyczasie:",
    meanwhileLink: "darmowy szablon open-to-buy w Excelu i checklista dashboardu KPI",
  },
  templates: {
    ...en.templates,
    seo: { title: "Darmowy szablon open-to-buy w Excelu i checklista dashboardu KPI", description: "Pobierz darmowy szablon open-to-buy w Excelu i checklistę dashboardu KPI dla Power BI." },
    eyebrow: "Darmowe szablony",
    h1: "Darmowy szablon open-to-buy w Excelu i checklista dashboardu KPI",
    intro: "Dwa pliki z prawdziwych projektów handlowych, wysyłane e-mailem. Treść zastępcza do czasu wgrania finalnych wersji.",
    items: [
      { title: "Szablon open-to-buy w Excelu do planowania", text: "Ilości, koszt, marża i rozłożenie w czasie z trzema kontrolami.", preview: "otb", previewCaption: "podgląd · arkusz open-to-buy" },
      { title: "Checklista dashboardu KPI dla Power BI", text: "Dwanaście kontroli przed udostępnieniem dashboardu zespołowi handlowemu.", preview: "checklist", previewCaption: "podgląd · checklista dashboardu" },
    ],
    checklist: ["Sell-through zdefiniowany i opisany", "Pokrycie zapasem per kategoria i rynek", "Udział pełnej ceny i głębokość obniżek", "Zwroty w tym samym modelu", "Jeden właściciel strony raportu"],
    insideTitle: "Co zawierają szablony do analityki handlowej",
    inside: [
      "Arkusz open-to-buy z rozłożeniem miesięcznym i marżą",
      "Zakładka krzywych rozmiarów i kolorów z oczyszczonej sprzedaży",
      "Arkusz definicji: jak i przez kogo liczony jest każdy KPI",
      "Checklista dashboardu z dwunastoma kontrolami",
      "Jednostronicowa notatka o przekazaniu modelu zespołowi",
    ],
    formTitle: "Otrzymaj oba szablony e-mailem",
    formText: "Jeden e-mail z dwoma plikami. Bez newslettera i bez udostępniania adresu.",
    panelTitle: "Darmowe szablony do analityki handlowej w Excelu i Power BI",
    panelText: "Tekst zastępczy: dwa pliki wysyłane e-mailem — model open-to-buy i checklista dashboardu KPI.",
    chips: ["Szablon open-to-buy w Excelu", "Checklista dashboardu KPI"],
    button: "Wyślij mi oba szablony",
    courseNote: "Kursy Power BI i Excel dla analityków handlu — wkrótce. Bez newslettera i bez udostępniania adresu.",
    relatedTitle: "Powiązane artykuły o analityce handlowej",
  },
  privacy: {
    seo: { title: "Polityka prywatności tatsianabandziuk.com", description: "Jak przetwarzane są dane z formularza kontaktowego, szablonów i listy oczekujących." },
    slug: "polityka-prywatnosci",
    eyebrow: "Informacje prawne · 2026",
    h1: "Polityka prywatności tatsianabandziuk.com",
    intro: "Jak przetwarzane są dane osobowe z formularza kontaktowego, darmowych szablonów i listy oczekujących. Tekst zastępczy do weryfikacji prawnej.",
    sections: [
      { id: "administrator", title: "1. Administrator danych i kontakt", text: "Tekst zastępczy: administratorem danych jest Tatsiana Bandziuk, Warszawa. Pytania: hello@tatsianabandziuk.com." },
      { id: "formularz", title: "2. Dane z formularza kontaktowego", text: "Tekst zastępczy: imię, firma, e-mail, opis zadania oraz opcjonalnie termin lub budżet — wyłącznie w celu odpowiedzi." },
      { id: "szablony", title: "3. Dane do szablonów i listy oczekujących", text: "Tekst zastępczy: adres e-mail do wysłania plików i jednej wiadomości o starcie kursu." },
      { id: "podstawa", title: "4. Podstawa prawna i okres przechowywania", text: "Tekst zastępczy: uzasadniony interes i zgoda; okres przechowywania do uzupełnienia." },
      { id: "cookies", title: "5. Pliki cookie i analityka", text: "Tekst zastępczy: niezbędne pliki cookie oraz, za zgodą, Google Analytics i Microsoft Clarity." },
      { id: "podmioty", title: "6. Podmioty przetwarzające", text: "Tekst zastępczy: hosting, poczta i analityka działają jako podmioty przetwarzające." },
      { id: "prawa", title: "7. Prawa wynikające z RODO", text: "Tekst zastępczy: dostęp, sprostowanie, usunięcie, ograniczenie, sprzeciw, przenoszenie i skarga do PUODO." },
      { id: "zmiany", title: "8. Zmiany polityki prywatności", text: "Tekst zastępczy: istotne zmiany zostaną ogłoszone na tej stronie." },
    ],
    note: "Uwaga: to szkic struktury, który przed publikacją musi sprawdzić prawnik.",
  },
  notFound: {
    eyebrow: "Błąd 404",
    h1: "Nie znaleziono strony na tatsianabandziuk.com",
    text: "Pod tym adresem nie ma danych. Wykres obok pokazuje, jak to wygląda w raporcie tygodniowym.",
    note: "Każdy zbiór danych ma gdzieś taki punkt.",
    chartLabel: "Sesje na tej stronie",
    nextTitle: "Dokąd przejść na stronie o analityce handlowej",
    links: [
      { title: "Usługi doradcze w analityce handlowej", text: "sześć usług i trzy formy współpracy", href: "/services" },
      { title: "Case studies z analityki handlu i mody", text: "zanonimizowane projekty z liczbami", href: "/case-studies" },
      { title: "Artykuły o analityce handlowej", text: "Power BI, Excel i asortyment", href: "/blog" },
      { title: "Kontakt w sprawie projektu analitycznego", text: "odpowiedź w ciągu dwóch dni roboczych", href: "/contact" },
    ],
  },
  thankYou: {
    contactTitle: "Dziękuję — zapytanie o projekt analityczny zostało wysłane",
    contactText: "Tekst zastępczy: każde zapytanie czytam osobiście i odpowiadam w ciągu dwóch dni roboczych, zwykle z kilkoma pytaniami o dane.",
    nextTitle: "Co dalej z Twoim zapytaniem",
    next: ["Odpowiedź z pierwszymi pytaniami — w ciągu dwóch dni roboczych", "Krótka rozmowa po angielsku, polsku lub rosyjsku", "Pisemny zakres, czas trwania i rezultaty"],
    caseStudiesLink: "Przeczytaj case studies",
    templatesLink: "Darmowe szablony",
    templatesTitle: "Sprawdź skrzynkę: szablon open-to-buy i checklista dashboardu są w drodze",
    templatesText: "Tekst zastępczy: oba pliki są w drodze. Jeśli nic nie dotrze w ciągu dziesięciu minut, sprawdź spam lub napisz bezpośrednio.",
    sent: "WYSŁANO",
    whileYouWait: "Zanim dotrą pliki: artykuły o analityce handlowej",
    close: "Zamknij i czytaj dalej",
  },
};
