import type { ConsultingFormat, Recommendation, Service, Tool } from "../../types";
import { services as en } from "../en/services";

const rec = (topic: string): Recommendation => ({
  quote: `„Tekst zastępczy rekomendacji. Dwa lub trzy zdania od współpracownika o ${topic}, cytowane za zgodą, gdy pojawi się prawdziwa rekomendacja.”`,
  name: "Imię Nazwisko",
  role: `Stanowisko · ${topic}`,
  placeholder: true,
});

const facts = (duration: string, deliverables: string) => [
  { label: "Czas trwania", value: duration },
  { label: "Forma", value: "online / na miejscu" },
  { label: "Języki", value: "EN / PL / RU" },
  { label: "Rezultat", value: deliverables },
];

const base = (slug: string) => en.find((s) => s.slug === slug)!;

export const services: Service[] = [
  {
    ...base("assortment-planning"),
    cardTitle: "Planowanie asortymentu i zarządzanie kolekcją",
    cardText: "Architektura kolekcji, liczba opcji i głębokość zakupu per rynek — tak, by zakup odpowiadał realnemu popytowi, a nie przyzwyczajeniom z zeszłego sezonu.",
    chartCaption: "krzywa rozmiarów · XS–3XL",
    breadcrumb: "Planowanie asortymentu",
    h1: { before: "Doradztwo w planowaniu asortymentu i zarządzaniu kolekcją dla", accent: "handlu modą" },
    intro: "Kolekcja oparta na danych: ile opcji w kategorii, jak głęboko w rozmiarach i kolorach oraz które rynki przejmują jaką część zakupu.",
    factsTitle: "Typowy projekt",
    facts: facts("6–10 tygodni", "plan kolekcji + model"),
    factsNote: "Zawsze zaczynam od Twoich danych sprzedażowych.",
    problemsTitle: "Problemy z asortymentem, które rozwiązuje to doradztwo",
    problems: [
      { title: "Za dużo opcji, za mało głębokości", text: "Kolekcja wygląda bogato na papierze, a w sklepie brakuje rozmiarów już w czwartym tygodniu." },
      { title: "Krzywe rozmiarów skopiowane z zeszłego sezonu", text: "Zwroty i braki towaru po cichu zniekształcają każdy kolejny zakup." },
      { title: "Jedna kolekcja dla bardzo różnych rynków", text: "Różnice w klimacie, cenach i wielkości sklepów pochłania potem obniżka cen." },
      { title: "Brak wspólnych liczb zakupów i finansów", text: "Każde spotkanie zaczyna się od uzgadniania dwóch wersji sell-through." },
    ],
    includesTitle: "Co obejmuje planowanie asortymentu i zarządzanie kolekcją",
    includesLead: "Pięć etapów realizowanych po kolei, każdy kończy się dokumentem dla Twojego zespołu.",
    includes: [
      { label: "01", title: "Przegląd architektury kategorii i kolekcji", text: "Liczba opcji według kategorii, progu cenowego i rynku na tle sell-through i marży." },
      { label: "02", title: "Wyliczenie krzywych rozmiarów i kolorów", text: "Krzywe z oczyszczonej sprzedaży: bez zwrotów, braków i tygodni promocji." },
      { label: "03", title: "Plan zakupów i model open-to-buy w Excelu", text: "Jeden model utrzymywany przez planistów: ilości, koszt, marża i rozłożenie w czasie." },
      { label: "04", title: "Monitoring kolekcji w sezonie w Power BI", text: "Tygodniowy sell-through, pokrycie zapasem i kompletność rozmiarów." },
      { label: "05", title: "Warsztaty przekazania dla zespołów zakupów i planowania", text: "Dwie sesje i dokumentacja, aby kolejny sezon działał bez konsultanta." },
    ],
    resultsTitle: "Wyniki klientów po doradztwie w planowaniu asortymentu",
    results: [
      { value: "+18", unit: "pp", label: "sell-through w kluczowych kategoriach w pierwszym pełnym sezonie" },
      { value: "−21", unit: "%", label: "liczby opcji przy większej głębokości sprawdzonych rozmiarów" },
      { value: "−31", unit: "%", label: "kosztów obniżek w dwóch kolejnych sezonach" },
    ],
    toolsTitle: "Narzędzia w projektach planowania asortymentu",
    tools: [
      { label: "fx", title: "Zaawansowany Excel w planie zakupów", text: "Open-to-buy, rozłożenie w czasie i scenariusze." },
      { label: "BI", title: "Power BI do monitoringu w sezonie", text: "Miary DAX dla sell-through, pokrycia i rozmiarów." },
      { label: "PLM", title: "Dane PLM jako podstawa kolekcji", text: "Czyste atrybuty kategorii, sezonu i koloru." },
    ],
    recommendationTitle: "Rekomendacja współpracownika z branży mody dotycząca planowania asortymentu",
    recommendation: rec("projekcie planowania asortymentu"),
    faqTitle: "Planowanie asortymentu — najczęstsze pytania",
    faq: [
      { question: "Jakiej historii sprzedaży potrzeba do przebudowy planu kolekcji?", answer: "Dwóch sezonów na poziomie SKU i tygodnia, ze stanami i zwrotami. Jeden sezon wystarczy, ale krzywe są mniej pewne." },
      { question: "Czy plan kolekcji może obejmować kilka rynków naraz?", answer: "Tak. Model zachowuje jedną architekturę kolekcji, a głębokość i rozmiary różnią się per rynek." },
      { question: "Kto utrzymuje model planu zakupów po projekcie?", answer: "Twój zespół planowania — model jest udokumentowany i przekazany podczas dwóch warsztatów." },
    ],
    ctaTitle: "Porozmawiaj z Tatsianą Bandziuk o projekcie planowania asortymentu",
    ctaText: "Tekst zastępczy: wyślij mi kategorię, co do której masz najwięcej wątpliwości. Odpowiem, co musiałyby pokazać dane.",
    seo: { title: "Doradztwo w planowaniu asortymentu dla handlu modą", description: "Architektura kolekcji, krzywe rozmiarów, model open-to-buy i monitoring w sezonie dla marek modowych. Konsultantka w Warszawie." },
  },
  {
    ...base("retail-pricing-analysis"),
    cardTitle: "Analiza cen w handlu detalicznym",
    cardText: "Drabinki cenowe, ceny wejścia i wyjścia, scenariusze marży i obniżek według kategorii i rynku.",
    chartCaption: "drabinka cenowa · wejście → najwyższy próg",
    breadcrumb: "Analiza cen",
    h1: { before: "Analiza cen w handlu detalicznym i ujednolicenie cen", accent: "między rynkami" },
    intro: "Drabinki cenowe zrozumiałe dla klienta i dla finansów: jasne progi w każdej kategorii, spójne między rynkami i sprawdzone pod kątem marży przed sezonem.",
    factsTitle: "Typowy projekt",
    facts: facts("4–8 tygodni", "drabinka cenowa + model marży"),
    factsNote: "Ceny sprawdzam na tle sell-through, nie tylko konkurencji.",
    problemsTitle: "Problemy cenowe, które rozwiązuje ta analiza",
    problems: [
      { title: "Luki i nakładanie się w drabince cenowej", text: "Zbyt bliskie ceny kanibalizują się, a pusty próg wysyła klientów do konkurencji." },
      { title: "Ten sam produkt w różnych cenach bez powodu", text: "Przeliczenia walut i lokalne decyzje rozjeżdżają się z czasem." },
      { title: "Obniżki z przyzwyczajenia", text: "Głębokość i termin rabatów powtarzają kalendarz z zeszłego sezonu." },
      { title: "Marża sprawdzana dopiero po sezonie", text: "Efekt zmian cen widać w raporcie dwa miesiące za późno." },
    ],
    includesTitle: "Co obejmuje analiza cen w handlu detalicznym",
    includesLead: "Cztery kroki, każdy kończy się plikiem dla właściciela cen.",
    includes: [
      { label: "01", title: "Audyt drabinki cenowej w kategoriach", text: "Progi wejścia, środka i topu na tle struktury sprzedaży i marży." },
      { label: "02", title: "Zasady ujednolicenia cen między rynkami", text: "Przeliczenia, zaokrąglenia i dopuszczalne odchylenia." },
      { label: "03", title: "Model scenariuszy marży i obniżek w Excelu", text: "Porównanie wariantów cen i rabatów przed decyzją." },
      { label: "04", title: "Monitoring cen w Power BI", text: "Tygodniowy przegląd ceny, marży i głębokości obniżek." },
    ],
    resultsTitle: "Wyniki klientów po analizie cen",
    results: [
      { value: "+2,4", unit: "pp", label: "marży brutto po uporządkowaniu drabinki" },
      { value: "3", label: "rynki wyceniane według jednych zasad" },
      { value: "−18", unit: "%", label: "głębokości obniżek w liniach podstawowych" },
    ],
    toolsTitle: "Narzędzia w projektach cenowych",
    tools: [
      { label: "fx", title: "Excel do scenariuszy cenowych", text: "Drabinki, przeliczenia i warianty marży." },
      { label: "BI", title: "Power BI do monitoringu cen", text: "Cena, marża i obniżki według tygodnia i rynku." },
      { label: "PLM", title: "Pola cenowe w PLM jako źródło", text: "Jeden właściciel i format każdego atrybutu ceny." },
    ],
    recommendationTitle: "Rekomendacja współpracownika z branży mody dotycząca pracy z cenami",
    recommendation: rec("projekcie cenowym"),
    faqTitle: "Analiza cen — najczęstsze pytania",
    faq: [
      { question: "Jakie dane są potrzebne do audytu drabinki cenowej?", answer: "Sprzedaż per SKU i tydzień z ceną sprzedaży, kosztem i rabatami za co najmniej jeden sezon." },
      { question: "Czy porównujesz nasze ceny z konkurencją?", answer: "Tak, jako jeden z elementów. Najważniejsza jest reakcja Twoich klientów na Twoje ceny." },
      { question: "Czy plan obniżek można przetestować przed startem?", answer: "Tak, model scenariuszy pokazuje marżę i zapas dla każdego wariantu." },
    ],
    ctaTitle: "Porozmawiaj z Tatsianą Bandziuk o projekcie cenowym",
    ctaText: "Tekst zastępczy: wyślij mi kategorię, w której ceny wydają się nietrafione. Odpowiem, co sprawdziłabym najpierw.",
    seo: { title: "Analiza cen i drabinki cenowej w handlu detalicznym", description: "Audyt drabinki cenowej, ujednolicenie cen między rynkami i scenariusze obniżek dla marek modowych." },
  },
  {
    ...base("power-bi-dashboards"),
    cardTitle: "Dashboardy Power BI dla KPI w handlu",
    cardText: "Sell-through, pokrycie zapasem, udział sprzedaży w pełnej cenie i zwroty w jednym modelu, który zespół handlowy naprawdę otwiera.",
    chartCaption: "układ dashboardu · schemat",
    breadcrumb: "Dashboardy Power BI",
    h1: { before: "Dashboardy Power BI dla KPI sprzedaży i", accent: "asortymentu" },
    intro: "Jeden model danych dla sell-through, pokrycia zapasem, sprzedaży w pełnej cenie i zwrotów — z definicjami uzgodnionymi przed pierwszym wykresem.",
    factsTitle: "Typowy projekt",
    facts: facts("4–8 tygodni", "model danych + raport"),
    factsNote: "Najpierw definicje, potem wykresy.",
    problemsTitle: "Problemy z raportowaniem, które rozwiązuje wdrożenie Power BI",
    problems: [
      { title: "Pięć raportów, pięć wersji sell-through", text: "Każdy zespół liczy ten sam KPI inaczej." },
      { title: "Raport miesięczny składany ręcznie", text: "Eksporty i poprawki zajmują dni." },
      { title: "Dashboardy, których nikt nie otwiera", text: "Raporty odpowiadają na pytania, których nikt nie zadał." },
      { title: "Liczba bez właściciela", text: "Nikt nie wie, kto może wyjaśnić podejrzany wynik." },
    ],
    includesTitle: "Co obejmuje wdrożenie dashboardów Power BI dla handlu",
    includesLead: "Od definicji do przekazania — pięć kroków.",
    includes: [
      { label: "01", title: "Arkusz definicji KPI uzgodniony z zespołami", text: "Każda miara z formułą, źródłem i właścicielem." },
      { label: "02", title: "Model danych handlowych w Power BI", text: "Sprzedaż, zapasy, dostawy, zwroty i atrybuty produktu." },
      { label: "03", title: "Miary DAX dla KPI w handlu", text: "Sell-through, tygodnie pokrycia, pełna cena, zwroty i marża." },
      { label: "04", title: "Strony raportu pod realne spotkania", text: "Przegląd tygodniowy, kategorii i końca sezonu." },
      { label: "05", title: "Odświeżanie, dostęp i przekazanie", text: "Harmonogram, zabezpieczenia na poziomie wierszy i dokumentacja." },
    ],
    resultsTitle: "Wyniki klientów po wdrożeniu dashboardów Power BI",
    results: [
      { value: "40", unit: "h", label: "miesięcznie mniej pracy nad raportami" },
      { value: "4 → 1", label: "konkurujące raporty zastąpione jednym modelem" },
      { value: "100", unit: "%", label: "KPI z definicją i właścicielem" },
    ],
    toolsTitle: "Narzędzia w projektach Power BI",
    tools: [
      { label: "BI", title: "Model danych Power BI i DAX", text: "Miary i zabezpieczenia na poziomie wierszy." },
      { label: "PQ", title: "Power Query do przygotowania danych", text: "Powtarzalne czyszczenie eksportów." },
      { label: "fx", title: "Excel jako arkusz definicji", text: "Jedno miejsce z opisem każdego KPI." },
    ],
    recommendationTitle: "Rekomendacja współpracownika z branży mody dotycząca raportowania w Power BI",
    recommendation: rec("raportowaniu w Power BI"),
    faqTitle: "Dashboardy Power BI dla handlu — najczęstsze pytania",
    faq: [
      { question: "Jakie dane są potrzebne do dashboardów KPI?", answer: "Sprzedaż, zapasy, dostawy i zwroty per SKU i tydzień oraz atrybuty produktu. Na start wystarczą eksporty z ERP lub PLM." },
      { question: "Czy potrzebujemy licencji Power BI Pro lub Premium?", answer: "Dla większości zespołów wystarczy Pro." },
      { question: "Czy dashboard można podzielić na rynki z ograniczonym dostępem?", answer: "Tak, dzięki zabezpieczeniom na poziomie wierszy." },
    ],
    ctaTitle: "Porozmawiaj z Tatsianą Bandziuk o raportowaniu w Power BI",
    ctaText: "Tekst zastępczy: wyślij mi raport, o który Twój zespół spiera się najczęściej.",
    seo: { title: "Dashboardy Power BI dla KPI w handlu", description: "Model danych, miary DAX i dashboardy Power BI dla sell-through, zapasów i marży w markach modowych." },
  },
  {
    ...base("excel-retail-planning-models"),
    cardTitle: "Modele Excel do planowania w handlu",
    cardText: "Open-to-buy, sezonowe plany zakupów i modele marży, które utrzymuje zespół, a nie konsultant.",
    chartCaption: "open-to-buy · sztuki, dane zastępcze",
    breadcrumb: "Modele planowania w Excelu",
    h1: { before: "Modele Excel do planowania w handlu i", accent: "analizy merchandisingowej" },
    intro: "Open-to-buy, plany zakupów i modele marży w narzędziu, którego planiści już używają — czytelne i łatwe w utrzymaniu.",
    factsTitle: "Typowy projekt",
    facts: facts("3–6 tygodni", "model Excel + instrukcja"),
    factsNote: "Model jest gotowy, gdy ktoś inny potrafi go prowadzić.",
    problemsTitle: "Problemy z planowaniem, które rozwiązuje model w Excelu",
    problems: [
      { title: "Plan zakupów zrozumiały tylko dla autora", text: "Ukryte arkusze i wpisane na sztywno liczby." },
      { title: "Open-to-buy rozjeżdża się w sezonie", text: "Dostawy i sprzedaż aktualizowane w różnych miejscach." },
      { title: "Scenariusze przez kopiowanie pliku", text: "Każdy wariant to nowa wersja pliku." },
      { title: "Marża liczona inaczej w każdej zakładce", text: "Niespójne koszty, rabaty i waluty." },
    ],
    includesTitle: "Co obejmuje model Excel do planowania w handlu",
    includesLead: "Cztery części w jednym skoroszycie z krótką instrukcją.",
    includes: [
      { label: "01", title: "Arkusz open-to-buy z rozłożeniem miesięcznym", text: "Ilości i wartość według miesiąca, kategorii i rynku." },
      { label: "02", title: "Plan zakupów i wyliczenie marży", text: "Spójna logika kosztów, cen, rabatów i walut." },
      { label: "03", title: "Porównanie scenariuszy bez kopii", text: "Przełączane założenia i zestawienie obok siebie." },
      { label: "04", title: "Wbudowane kontrole i instrukcja", text: "Trzy kontrole i opis dla kolejnego właściciela." },
    ],
    resultsTitle: "Wyniki klientów po wdrożeniu modeli w Excelu",
    results: [
      { value: "1", label: "skoroszyt zamiast sezonowych kopii" },
      { value: "−70", unit: "%", label: "czasu aktualizacji open-to-buy" },
      { value: "3", label: "automatyczne kontrole" },
    ],
    toolsTitle: "Narzędzia w projektach planowania w Excelu",
    tools: [
      { label: "fx", title: "Formuły i tabele Excela", text: "Tabele strukturalne i tablice dynamiczne." },
      { label: "PQ", title: "Import przez Power Query", text: "Dane bez kopiowania." },
      { label: "BI", title: "Power BI do monitoringu", text: "Plan kontra wykonanie." },
    ],
    recommendationTitle: "Rekomendacja współpracownika z branży mody dotycząca modeli planistycznych",
    recommendation: rec("modelu planistycznym"),
    faqTitle: "Modele planowania w Excelu — najczęstsze pytania",
    faq: [
      { question: "Dlaczego Excel, a nie system planistyczny?", answer: "Wiele zespołów najpierw potrzebuje przejrzystego modelu. Dobry model staje się potem specyfikacją systemu." },
      { question: "Czy możesz przebudować nasz obecny plik?", answer: "Tak, najpierw dokumentuję istniejącą logikę." },
      { question: "Jaka wersja Excela jest potrzebna?", answer: "Zalecany Microsoft 365." },
    ],
    ctaTitle: "Porozmawiaj z Tatsianą Bandziuk o modelu planowania w Excelu",
    ctaText: "Tekst zastępczy: opisz plik, którego planiści boją się dotykać.",
    seo: { title: "Modele open-to-buy i planu zakupów w Excelu", description: "Modele open-to-buy, planu zakupów i marży w Excelu dla planistów w handlu modą." },
  },
  {
    ...base("product-data-quality-plm"),
    cardTitle: "Jakość danych produktowych i standaryzacja danych w PLM",
    cardText: "Jeden słownik atrybutów dla wszystkich rynków: czyste sezony, kolory, składy i kody w systemie PLM.",
    chartCaption: "kompletność atrybutów · dane zastępcze",
    breadcrumb: "Dane produktowe i PLM",
    h1: { before: "Jakość danych produktowych i standaryzacja danych PLM dla", accent: "marek modowych" },
    intro: "Jeden słownik atrybutów dla każdego rynku, walidacja przy wprowadzaniu i dashboard jakości danych.",
    factsTitle: "Typowy projekt",
    facts: facts("6–12 tygodni", "słownik + reguły + dashboard"),
    factsNote: "Prawdziwym projektem jest uzgodnienie słownika.",
    problemsTitle: "Problemy z danymi produktowymi, które rozwiązuje ta usługa",
    problems: [
      { title: "Kolor zapisany na cztery sposoby", text: "Wolny tekst uniemożliwia filtrowanie i raportowanie." },
      { title: "Niezgodne kody sezonów", text: "Rynki różnie definiują początek sezonu." },
      { title: "Puste pola odkryte za późno", text: "Produkty trafiają do e-commerce bez składu i kategorii." },
      { title: "Ręczne czyszczenie przed każdym raportem", text: "Dni pracy co miesiąc." },
    ],
    includesTitle: "Co obejmuje standaryzacja danych produktowych",
    includesLead: "Cztery etapy — od audytu do comiesięcznego przeglądu.",
    includes: [
      { label: "01", title: "Audyt atrybutów produktów per rynek", text: "Każde pole zmapowane i ocenione." },
      { label: "02", title: "Słownik atrybutów uzgodniony z rynkami", text: "Kolor, sezon, skład i kategoria zdefiniowane raz." },
      { label: "03", title: "Reguły migracji i walidacja w PLM", text: "Dane historyczne przemapowane, nowe produkty sprawdzane przy wprowadzaniu." },
      { label: "04", title: "Dashboard jakości danych i przegląd miesięczny", text: "Kompletność per atrybut i rynek z właścicielem." },
    ],
    resultsTitle: "Wyniki klientów po standaryzacji danych produktowych",
    results: [
      { value: "98", unit: "%", label: "kompletności atrybutów" },
      { value: "−60", unit: "%", label: "czasu na poprawianie danych" },
      { value: "3", unit: "dni", label: "ręcznego czyszczenia mniej co miesiąc" },
    ],
    toolsTitle: "Narzędzia w projektach danych PLM",
    tools: [
      { label: "PLM", title: "Konfiguracja systemu PLM", text: "Listy atrybutów i reguły walidacji." },
      { label: "fx", title: "Excel i Power Query do mapowania", text: "Przemapowanie danych historycznych." },
      { label: "BI", title: "Dashboard jakości danych w Power BI", text: "Kompletność per atrybut i rynek." },
    ],
    recommendationTitle: "Rekomendacja współpracownika z branży mody dotycząca danych produktowych",
    recommendation: rec("projekcie danych produktowych"),
    faqTitle: "Dane produktowe i PLM — najczęstsze pytania",
    faq: [
      { question: "Z jakimi systemami PLM pracujesz?", answer: "Metoda nie zależy od systemu." },
      { question: "Ile trwa uzgodnienie słownika atrybutów?", answer: "Zwykle od trzech do pięciu tygodni." },
      { question: "Czy można oczyścić też produkty historyczne?", answer: "Tak, dzięki regułom migracji." },
    ],
    ctaTitle: "Porozmawiaj z Tatsianą Bandziuk o projekcie danych produktowych",
    ctaText: "Tekst zastępczy: wyślij mi trzy atrybuty, które sprawiają najwięcej kłopotu.",
    seo: { title: "Jakość danych produktowych i standaryzacja PLM", description: "Słownik atrybutów, reguły walidacji w PLM i dashboard jakości danych dla marek modowych." },
  },
  {
    ...base("retail-analytics-processes"),
    cardTitle: "Organizacja procesów analitycznych w handlu",
    cardText: "Kalendarz raportów, właściciele, definicje i rytm przeglądów — liczby uzgadnia się raz i używa wszędzie.",
    chartCaption: "kalendarz raportów · tydzień / miesiąc / kwartał",
    breadcrumb: "Procesy analityczne",
    h1: { before: "Organizacja procesów analitycznych i", accent: "zespołów raportowych" },
    intro: "Kalendarz raportów, właściciele i uzgodnione definicje, aby spotkania służyły decyzjom, a nie sprawdzaniu liczb.",
    factsTitle: "Typowy projekt",
    facts: facts("4–8 tygodni", "kalendarz + role + playbook"),
    factsNote: "Raport bez właściciela po miesiącu przestaje być prawdziwy.",
    problemsTitle: "Problemy zespołów i procesów, które rozwiązuje ta usługa",
    problems: [
      { title: "Raporty w przypadkowych terminach", text: "Nikt nie wie, która wersja jest ostateczna." },
      { title: "Analizy robi ten, kto ma czas", text: "Role się dublują i zostawiają luki." },
      { title: "Definicje w głowach ludzi", text: "Odejście pracownika zabiera logikę raportów." },
      { title: "Przeglądy bez decyzji", text: "Działania nie są zapisywane ani sprawdzane." },
    ],
    includesTitle: "Co obejmuje organizacja procesów analitycznych",
    includesLead: "Cztery elementy trwałej rutyny raportowej.",
    includes: [
      { label: "01", title: "Kalendarz raportów", text: "Raporty tygodniowe, miesięczne i sezonowe z terminami." },
      { label: "02", title: "Macierz ról i odpowiedzialności", text: "Kto przygotowuje, sprawdza i objaśnia." },
      { label: "03", title: "Playbook definicji i standardów danych", text: "KPI i reguły w jednym dokumencie." },
      { label: "04", title: "Rytm przeglądów i dziennik decyzji", text: "Spotkania kończące się właścicielem i terminem." },
    ],
    resultsTitle: "Wyniki klientów po uporządkowaniu procesów analitycznych",
    results: [
      { value: "1", label: "kalendarz raportów dla wszystkich zespołów" },
      { value: "100", unit: "%", label: "raportów z właścicielem" },
      { value: "−50", unit: "%", label: "czasu na uzgadnianie liczb" },
    ],
    toolsTitle: "Narzędzia w projektach procesowych",
    tools: [
      { label: "fx", title: "Macierz odpowiedzialności w Excelu", text: "Zadania, właściciele i zastępcy." },
      { label: "BI", title: "Katalog raportów Power BI", text: "Który raport na jakie pytanie." },
      { label: "PLM", title: "Standardy danych PLM", text: "Reguły wprowadzania danych." },
    ],
    recommendationTitle: "Rekomendacja współpracownika z branży mody dotycząca kierowania zespołem",
    recommendation: rec("kierowaniu zespołem danych produktowych"),
    faqTitle: "Procesy analityczne — najczęstsze pytania",
    faq: [
      { question: "Czy to usługa tylko dla dużych zespołów?", answer: "Nie, najwięcej zyskują małe zespoły." },
      { question: "Czy pracujesz na naszych narzędziach?", answer: "Tak, proces projektuję wokół istniejących raportów." },
      { question: "Czy szkolisz zespół?", answer: "Tak, szkolenie i playbook są częścią przekazania." },
    ],
    ctaTitle: "Porozmawiaj z Tatsianą Bandziuk o procesach analitycznych",
    ctaText: "Tekst zastępczy: opisz, jak dziś powstaje Twój raport tygodniowy.",
    seo: { title: "Procesy analityczne i zespoły raportowe w handlu", description: "Kalendarz raportów, macierz odpowiedzialności i definicje KPI dla zespołów analitycznych w modzie." },
  },
];

export const formats: ConsultingFormat[] = [
  {
    label: "FORMAT 01",
    title: "Dwutygodniowa diagnostyka danych handlowych",
    suits: "markom, które podejrzewają błędy w kolekcji lub cenach, ale nie mogą tego udowodnić swoimi raportami.",
    youGet: "raport z ustaleniami, policzone luki i plan priorytetów.",
    duration: "2 tygodnie",
    cta: "Zamów diagnostykę",
  },
  {
    label: "FORMAT 02",
    title: "Projekt: asortyment, ceny lub raportowanie",
    suits: "zespołom z jednym jasnym problemem — planem kolekcji, drabinką cenową, danymi PLM lub raportami KPI.",
    youGet: "działające modele lub dashboardy, dokumentację i przekazanie zespołowi.",
    duration: "6–10 tygodni",
    cta: "Omów projekt",
  },
  {
    label: "FORMAT 03",
    title: "Stałe wsparcie analityczne",
    suits: "rosnącym markom bez własnego analityka, które potrzebują stałego miesięcznego rytmu.",
    youGet: "utrzymywane raporty, miesięczny przegląd i zapisane decyzje.",
    duration: "abonament miesięczny",
    cta: "Zapytaj o wsparcie",
  },
];

export const tools: Tool[] = [
  { id: "power-bi", monogram: "BI", title: "Power BI w raportowaniu handlowym", text: "Jeden model danych dla marki: sell-through, pokrycie zapasem i marża bez ręcznej pracy.", skills: ["DAX", "Power Query", "zabezpieczenia wierszy"] },
  { id: "excel", monogram: "fx", title: "Zaawansowany Excel w modelach planowania", text: "Plany zakupów, open-to-buy i scenariusze marży, które planiści potrafią prowadzić.", skills: ["open-to-buy", "scenariusze", "modele pivot"] },
  { id: "plm", monogram: "PLM", title: "Systemy PLM dla danych produktowych", text: "Słowniki atrybutów, struktury sezonów i kolorów oraz reguły czystych danych.", skills: ["słownik atrybutów", "zarządzanie danymi"] },
];

export const recommendations: Recommendation[] = [
  { quote: "„Tekst zastępczy rekomendacji. Kilka zdań o tym, jak analiza asortymentu zmieniła decyzje zespołu zakupów.”", name: "Imię Nazwisko", role: "Stanowisko · wspólna praca nad asortymentem", placeholder: true },
  { quote: "„Tekst zastępczy rekomendacji. Kilka zdań o raportach Power BI, o których przestano się spierać.”", name: "Imię Nazwisko", role: "Stanowisko · ten sam zespół marki", placeholder: true },
  { quote: "„Tekst zastępczy rekomendacji. Krótko o pracy z danymi produktowymi w PLM i przekazaniu standardu zespołowi.”", name: "Imię Nazwisko", role: "Stanowisko · projekt danych produktowych", placeholder: true },
];
